### ISSUE TITLE
Worker node not registered

### ISSUE THREAD

**Issue by sharmmoh1983** [mmumshad/kubernetes-the-hard-way#101]
When I run kubectl get nodes . I am getting following error

node "worker-1" not found

**Comment by lalitkumarbansal** [comment]
I am also facing same issue... 

first problem was in /var/lib/kubelet/kube-config file ... there ${LOAD_BLANCER_IP} was not getting replaced, once I corrected that I started getting following problem ...

I tried running following command and from logs I found this
> sudo journalctl -u kubelet

invalid kubeconfig: invalid configuration: no configuration

**Comment by fireflycons** [comment]
Hi @sharmmoh1983 @lalitkumarbansal 

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. 
I realise this is a very old issue, however I was tasked with closing off all old issues following the upgrade.
Please try it now and feel free to raise further issues.

Thanks.
