### ISSUE TITLE
Kubernetes hardway while setup the etcd cluster.Re: [kubernetes/kubeadm] [root@kubemaster system]# ETCDCTL_API=3 etcdctl member list --endpoints=https://127.0.0.1:2379 --cacert=/etc/etcd/ca.crt --cert=/etc/etcd/etcd-server.crt --key=/etc/etcd/etcd-server.key {"level":"warn","ts":"2020-03-23T12:47:38.622-0400","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-99894cc2-a3c5-4ecf-b869-52c4d121fc1b/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""} Error: context deadline exceeded [root@kubemaster system]# (#2070

### ISSUE THREAD

**Issue by sarath4** [mmumshad/kubernetes-the-hard-way#103]
Re: [kubernetes/kubeadm] [root@kubemaster system]# ETCDCTL_API=3 etcdctl member list --endpoints=https://127.0.0.1:2379 --cacert=/etc/etcd/ca.crt --cert=/etc/etcd/etcd-server.crt --key=/etc/etcd/etcd-server.key {"level":"warn","ts":"2020-03-23T12:47:38.622-0400","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-99894cc2-a3c5-4ecf-b869-52c4d121fc1b/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""} Error: context deadline exceeded [root@kubemaster system]# (#2070

Am trying to configure kubernetes hardway while setup the etcd cluster.
My configuration:
[root@kubemaster system]# cat etcd.service
[Unit]
Description=etcd
Documentation=https://github.com/coreos

[Service]
ExecStart=/usr/local/bin/etcd
--advertise-client-urls=https://192.168.86.128:2379
--cert-file=/etc/etcd/etcd-server.crt
--client-cert-auth=true
--data-dir=/var/lib/etcd
--initial-advertise-peer-urls=https://192.168.86.128:2380
--initial-cluster=master=https://192.168.86.128:2380
--key-file=/etc/etcd/etcd-server.key
--listen-client-urls=https://127.0.0.1:2379,https://192.168.86.128:2379
--listen-metrics-urls=http://127.0.0.1:2381
--listen-peer-urls=https://192.168.86.128:2380
--name=kubemaster
--peer-cert-file=/etc/etcd/etcd-server.crt
--peer-client-cert-auth=true
--peer-key-file=/etc/etcd/etcd-server.key
--peer-trusted-ca-file=/etc/etcd/ca.crt
--snapshot-count=10000
--trusted-ca-file=/etc/etcd/ca.crt

Restart=on-failure
RestartSec=5
[Install]
WantedBy=multi-user.target
[root@kubemaster system

**Comment by fireflycons** [comment]
Hi @sarath4 

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. 
I realise this is a very old issue, however I was tasked with closing off all old issues following the upgrade.
Please try it now and feel free to raise further issues.

Thanks.
