### ISSUE TITLE
[Lecture Needed][CKA]How to create private repo in kubernetes

### ISSUE THREAD

**Issue by manojb1** [mmumshad/kubernetes-the-hard-way#104]
Could you please involve lectures about **creating private registry in kubernetes?** This will be necessary to uploading the container images in centralised repository.

**Comment by fireflycons** [comment]
Hi @manojb1 

Managing private registries is not in curriculum for CKA/CKAD exams so a lecture wouldn't be provided.

All the major cloud providers have managed registry offerings so you can follow their documentation to set one up. Alternatively you can deploy an artifact manager such as Artifactory, ProGet, Nexus etc. to have on-prem container registries.
