### ISSUE TITLE
[Solution] Bootstrapping Kubernetes workers - config file

### ISSUE THREAD

**Issue by santipioli** [mmumshad/kubernetes-the-hard-way#107]
I ran into a problem when I was trying to get up workers nodes. The documentation use these two flagas while configuring the kubelet.service

`--tls-cert-file=/var/lib/kubelet/${HOSTNAME}.crt \\
  --tls-private-key-file=/var/lib/kubelet/${HOSTNAME}.key \\`

The error is that those flags are depricated and the kubelet service won't run. The solution is by adding ths tls certificates information into the config file "--config=/var/lib/kubelet/kubelet-config.yaml".
Adding this two lines at the end of the file the problem is solved (without indentation):

`tlsCertFile: "/var/lib/kubelet/${HOSTNAME}.crt"
tlsPrivateKeyFile: "/var/lib/kubelet/${HOSTNAME}.key"`

I got this info from [Kelsey Hightowers](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/09-bootstrapping-kubernetes-workers.md) repo.

Also after that I had an error about swap. I don't know exactly the source of this error but the solution is by turning off the swap in the worker node:

`sudo swapoff -a`

I faced this swap issue using VMWare Fusion (in MacOS) for this lab.

Hope it helps someone.

**Comment by fgauna12** [comment]
@santipioli - I am also using VMWare (VMWare workstation). It helped me. Thanks!

**Comment by fireflycons** [comment]
Hi @fgauna12 @santipioli 

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. 
I realise this is a very old issue, however I was tasked with closing off all old issues following the upgrade.
Please try it now and feel free to raise further issues.

Thanks.
