### ISSUE TITLE
Kubernetes Operators

### ISSUE THREAD

**Issue by itsmesuniljacob** [mmumshad/kubernetes-the-hard-way#117]
Great to have a lecture on Kubernetes Operators

**Comment by steevivo** [comment]
@xylene1980 

https://www.magalix.com/blog/creating-custom-kubernetes-operators
https://www.youtube.com/watch?time_continue=3&v=i9V4oCa5f9I&feature=emb_logo

**Comment by fireflycons** [comment]
Hi @itsmesuniljacob 

Operators are touched upon in CKAD course. You have to know what they are and where they might be used, but not how to create one.

You can raise requests for new courses by going to the following link. If something similar to what you're looking for is already present in the list, simply upvote it else add a new request.
Thanks.

https://kodekloud.com/request-a-course/
