### ISSUE TITLE
Networking Kubernetes using project Calico - Lecture Request

### ISSUE THREAD

**Issue by tumhaar-bitua** [mmumshad/kubernetes-the-hard-way#120]
I heard about projectcalico.org (Networking for Kubernetes) that is being used with Kubernetes for one of my friend's project and I am curious if you have anything on that topic.

**Comment by fireflycons** [comment]
Hi @tumhaar-bitua 

You can raise requests for new courses by going to the following link. If something similar to what you're looking for is already present in the list, simply upvote it else add a new request.
Thanks.

https://kodekloud.com/request-a-course/
