### ISSUE TITLE
kubetest not found

### ISSUE THREAD

**Issue by msadofschi** [mmumshad/kubernetes-the-hard-way#123]
need some help while trying to make the e2e test in the k8s the hard way
[16-e2e-tests.md](https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/16-e2e-tests.md)
After I install kubetest:
`go get -v -u k8s.io/test-infra/kubetest`
Then kubetest binary is not found
```
kubetest --extract=v1.14.1
kubetest: command not found
```
Can someone help please?

**Comment by an-t-oine** [comment]
same issue

**Comment by blasterspike** [comment]
Run again `go get -v -u k8s.io/test-infra/kubetest` and check if you get a meaningful error.
I suggest you to follow this other issue as well as it might be related:
https://github.com/mmumshad/kubernetes-the-hard-way/issues/115

**Comment by fireflycons** [comment]
Hi @msadofschi @an-t-oine @blasterspike 

We have now merged a major change to bring this to v1.24.
Many issues including this have been addressed as part of the upgrade. Please try it now and feel free to raise further issues.

Also note that in the 11 versions that have been jumped, kubetest now has _significantly_ more tests, and takes 18+ hours to run to completion. Not all tests it runs are valid for this setup, so a small percentage of failures is expected.

Thanks.
