### ISSUE TITLE
10-tls-bootstrapping-kubernetes-workers -  localhost:8080 was refused

### ISSUE THREAD

**Issue by edwint88** [mmumshad/kubernetes-the-hard-way#124]
After doing all the previous steps 1 to 9 flawless, doing step 10 I have the following problem:

`kubectl create -f bootstrap-token-07401b.yaml`
> The connection to the server localhost:8080 was refused - did you specify the right host or port?

- I tried to change the ip of `KUBERNETES_MASTER=` to the master-1 and the lb and nothing seems to work.

- Also I tried to run `sudo swapoff -a` as some online post suggested, but also without any luck.

Do you have any ideas what can be wrong there?

**Comment by edwint88** [comment]
TLDR run on master-1 not worker-2!

the problem was that I ran all the commands on worker-2 and the bootstrap token and the following commands should be executed on the master-1, which this was missing in the steps documentation. This was just a misunderstanding, because of the jumping from installing the tools on worker-2 and then no heads up that the other commands should run on master.

**Comment by fireflycons** [comment]
Hi @edwint88 

We have now merged a major change to bring this to v1.24.
Many issues including this have been addressed as part of the upgrade. Please try it now and feel free to raise further issues.

Thanks.
