### ISSUE TITLE
 Running commands in parallel with tmux link is broken

### ISSUE THREAD

**Issue by sharjeelsayed** [mmumshad/kubernetes-the-hard-way#125]
[Running commands in parallel with tmux](https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/01-prerequisites.md#running-commands-in-parallel-with-tmux) link is broken

**Comment by kulkravi** [comment]
Bump!

**Comment by fireflycons** [comment]
Hi @sharjeelsayed  @kulkravi 

We have now merged a major change to bring this to v1.24.
Many issues including this have been addressed as part of the upgrade. Please try it now and feel free to raise further issues.

Thanks.
