### ISSUE TITLE
Kube proxy CRT copy over

### ISSUE THREAD

**Issue by susilkumarjayachandran** [mmumshad/kubernetes-the-hard-way#126]
Were kube-proxy.key, kube-proxy.crt, kube-scheduler.key, kube-scheduler.crt, admin.key, admin.crt copy over to master-2 missed in https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md

**Comment by fireflycons** [comment]
Hi @susilkumarjayachandran 

As per comment on the other issue, please try new version

Thanks
