### ISSUE TITLE
no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1"

### ISSUE THREAD

**Issue by susilkumarjayachandran** [mmumshad/kubernetes-the-hard-way#127]
> kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

kubectl create clusterrolebinding auto-approve-csrs-for-group --clusterrole=system:certificates.k8s.io:certificatesigningrequests:nodeclient --group=system:bootstrappers

Error
===

error: no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"

metadata:
  name: create-csrs-for-bootstrapping
subjects:
- kind: Group
  name: system:bootstrappers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: system:node-bootstrapper
  apiGroup: rbac.authorization.k8s.io

kubectl create -f csrs-for-bootstrapping.yaml

error: unable to recognize "csrs-for-bootstrapping.yaml": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1"

**Comment by fireflycons** [comment]
Hi @susilkumarjayachandran 

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. Please try it now and feel free to raise further issues.

Thanks.
