### ISSUE TITLE
unable to load CA Private Key - when generating worker-1 crt file

### ISSUE THREAD

**Issue by jainmnsh** [mmumshad/kubernetes-the-hard-way#132]
Hello, I am on 09-bootstrapping-kubernetes-workers.md steps, so far my controller plain and load balancers setup as defined but I am getting below error when I am trying to generate worker node CRT file from master-1 node - I verified all same key that works for other processes.

penssl x509 -req -in worker-1.csr -CA ca.crt -CAkey ca.key -CAcreateserial  -out worker-1.crt -extensions v3_req -extfile openssl-worker-1.cnf -days 1000
Signature ok
subject=CN = system:node:worker-1, O = system:nodes
Getting CA Private Key
unable to load CA Private Key
139925635920320:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: ANY PRIVATE KEY

**Comment by fireflycons** [comment]
Hi @jainmnsh 

Looks like the PEM format of the key file is corrupted. You should recreate the PKI.

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. Please try it now and feel free to raise further issues.

Thanks.
