### ISSUE TITLE
typo erros in below section

### ISSUE THREAD

**Issue by saikantgajula** [mmumshad/kubernetes-the-hard-way#134]
Below command has typo's. Please correct it.

Copy the appropriate admin.kubeconfig, kube-controller-manager and kube-scheduler kubeconfig files to each controller instance:

for instance in master-1 master-2; do
  scp admin.kubeconfig kube-controller-manager.kubeconfig kube-scheduler.kubeconfig ${instance}:~/
done

Correct command.

```
for instance in master-1 master-2; do
  scp admin.kubeconfig kube-controller-manager  kube-scheduler  ${instance}:~/
done
```

**Comment by fireflycons** [comment]
Hi @saikantgajula 

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. Please try it now and feel free to raise further issues.

Thanks.
