### ISSUE TITLE
Update core components to latest June 2020

### ISSUE THREAD

**Issue by tringuyen-yw** [mmumshad/kubernetes-the-hard-way#139]
From the [README](https://github.com/mmumshad/kubernetes-the-hard-way):

> * [Kubernetes](https://github.com/kubernetes/kubernetes) 1.13.0
> * [Docker Container Runtime](https://github.com/containerd/containerd) 18.06
> * [CNI Container Networking](https://github.com/containernetworking/cni) 0.7.5
> * [Weave Networking](https://www.weave.works/docs/net/latest/kubernetes/kube-addon/)
> * [etcd](https://github.com/coreos/etcd) v3.3.9
> * [CoreDNS](https://github.com/coredns/coredns) v1.2.2

The versions used above are more than 1 year old. I notice the last update of the [upstream repo](https://github.com/kelseyhightower/kubernetes-the-hard-way) is 9 months old (Sep 2019). However still more up to date than the versions used here.

As of June 2020, the latest release are:

- Kubernetes [1.18.3](https://github.com/kubernetes/kubernetes/releases/tag/v1.18.3)
- Docker Container Runtime [19.03.11](https://github.com/docker/docker-ce/releases/tag/v19.03.11)
- containerd [1.3.4](https://github.com/containerd/containerd/releases/tag/v1.3.4)
- etcd [3.4.9](https://github.com/etcd-io/etcd/releases/tag/v3.4.9)
- CoreDNS [1.6.9](https://github.com/coredns/coredns/releases/tag/v1.6.9)

Kubernetes is a fast moving ecosystem. I believe it is worthwhile for students to work on most recent versions. Would it be OK to make a refresh of the installation scripts to use latest versions?

**Comment by fireflycons** [comment]
Hi @tringuyen-yw 

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. Please try it now and feel free to raise further issues.

Thanks.
