### ISSUE TITLE
[Learning CKAD] In ReplicaSet question cause ambiguity with delete a pod & check fails

### ISSUE THREAD

**Issue by robin-carry** [mmumshad/kubernetes-the-hard-way#140]
There is a question which specifies to delete a pod out of the 4 which are created using replicaset. 

If someone deletes a pod by scaling down the replicaset, a pod is actually getting deleted and the "Check" passes the question. 

What causes the problem is the next question asks how many pods are present (which is 3), but expect the answer 4. 

May be hint with the question is to make sure to ONLY delete pods.

**Comment by robin-carry** [comment]
PS: No way to assign labels - seems like don't have auth to do it.

**Comment by fireflycons** [comment]
Hi @robin-carry 

We have a community forum for this sort of question. Please raise at https://community.kodekloud.com/

Thanks

**Comment by robin-carry** [comment]
This is 2yrs old question (even I forgot about it) + I got CKAD/CKA... and other certificates long back. 

Thank you so much for the content.

**Comment by fireflycons** [comment]
No worries @robin-carry 
I was tasked with closing down all the old issues following the repo update :-)
