### ISSUE TITLE
if  i want to use flannal or calico,  what will i do?

### ISSUE THREAD

**Issue by realzhangqingwei** [mmumshad/kubernetes-the-hard-way#147]
if  i want to use flannal or calico,  what will i do?

**Comment by realzhangqingwei** [comment]
who can help me?  thanks

**Comment by fireflycons** [comment]
Hi @realzhangqingwei 

You need to not run the command that installs the weave manifests, and instead follow the documentation on your chosen CNI provider's website.

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. Please try it now and feel free to raise further issues.

Thanks.
