### ISSUE TITLE
VM Provisioning failing with following errors

### ISSUE THREAD

**Issue by fekezue** [mmumshad/kubernetes-the-hard-way#149]
VM provisioning is failing at the worker-1 VM with following errors. Deleted VM several times and got the same errors   

    worker-1: # Executing docker install script, commit: 26ff363bcf3b3f5a00498ac43694bf1c7d9ce16c
    worker-1: +
    worker-1: sh
    worker-1:  -c
    worker-1:  apt-get update -qq >/dev/null
    worker-1: + sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
    worker-1: + sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
    worker-1: Warning: apt-key output should not be parsed (stdout is not a terminal)
    worker-1: + sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" > /etc/apt/sources.list.d/docker.list
    worker-1: + sh -c apt-get update -qq >/dev/null
    worker-1: +
    worker-1: [ -n  ]
    worker-1: + sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
    worker-1: E
    worker-1: :
    worker-1: Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/containerd.io_1.2.13-2_amd64.deb  Hash Sum mismatch
    worker-1:    Hashes of expected file:
    worker-1:     - SHA512:4261d170fe1962df2f73efffb5f438b93cd3cbd050f02a66171e55f2b323799814c4ecb464b582a28ace1a7fc5a3b3470643bfe718c1a72008a21462f79a6808
    worker-1:     - SHA256:e5fd0f73fe2a83b0030af490ba5b26eec79483059a7ff7873c47948ff3fbb864
    worker-1:     - SHA1:38cc415af5a03198a2f83bd49307ad329b45ff06 [weak]
    worker-1:     - MD5Sum:84488c696235a78a5be963c13ed2aadf [weak]
    worker-1:     - Filesize:21400958 [weak]
    worker-1:    Hashes of received file:
    worker-1:     - SHA512:5d410623bdc9f12117e89825fa596e649d643aec26414216beb7e21a3b537c81073eca77b77e9eed69e102e5eb44826847d16b0666d24a161ac13e7ecc929462
    worker-1:     - SHA256:d756eaf0d64719b45948a568a7c4ea7bf2aa58d0e7d6b6b916cdaade9cb460a9
    worker-1:     - SHA1:706524b05a70ee4c05ce9e06f087d85cda322cc4 [weak]
    worker-1:     - MD5Sum:b4a4bcea3d5db295971aab9d6d4dfb2e [weak]
    worker-1:     - Filesize:21400958 [weak]
    worker-1:    Last modification reported: Fri, 15 May 2020 03:16:17 +0000
    worker-1: E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce-cli_19.03.12~3-0~ubuntu-bionic_amd64.deb  Hash Sum mismatch
    worker-1:    Hashes of expected file:
    worker-1:     - SHA512:41bbdc739281b5bd0dca419f1947292094cb0adb855f039249ac20705ead259299635e00724a277de50fc0b84d69ba7a6cd8889cd6a5982749b707b0a592dc96
    worker-1:     - SHA256:8764cce6b7d366d1c4bd2ddb8fa27081fa3626a1a545e288612019d968b61eef
    worker-1:     - SHA1:0ba870c5ed1fc849b7bf6160380f40471ced6032 [weak]
    worker-1:     - MD5Sum:5ffd2439e52efed2483e1e240a1a2765 [weak]
    worker-1:     - Filesize:41183314 [weak]
    worker-1:    Hashes of received file:
    worker-1:     - SHA512:0824022dc997ec906a354ecc8e0a2865562e30f3c26c05624044439bf1b4b8a86443046b1d89771cefca0a0c607fea7b49cd2550bdd2b02ce5feb04757dfeb0c
    worker-1:     - SHA256:6c643cfb73f27d98457e3101c41f9a82cb190472aba8056bd83c3d56c707f540
    worker-1:     - SHA1:51dcf87ea90a17b3c463dcd5c6c2a5d602172137 [weak]
    worker-1:     - MD5Sum:b40cef07a6c8e042ccee47b37256ccd8 [weak]
    worker-1:     - Filesize:41183314 [weak]
    worker-1:    Last modification reported: Tue, 23 Jun 2020 01:50:46 +0000
    worker-1: E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce_19.03.12~3-0~ubuntu-bionic_amd64.deb  Hash Sum mismatch
    worker-1:    Hashes of expected file:
    worker-1:     - SHA512:b744c7401a7c4acf30a45bc9eec8fb8fded115c6c83eee808c5672d912b156dfad78e5439588e3db7bfcc7a66d47a1d346aa4797d1939734c19e6ce77bc6bef3
    worker-1:     - SHA256:3faca0c8a8299d8f138354eebc9a3fd84fa07e1e7566632014716bc9ac3ca57c
    worker-1:     - SHA1:09e0def531dafd8dad324a87c0dfe73a8e2a78b6 [weak]
    worker-1:     - MD5Sum:bd4c9cabe06da80458e2850c4cb916ea [weak]
    worker-1:     - Filesize:22530546 [weak]
    worker-1:    Hashes of received file:
    worker-1:     - SHA512:80375ff424d7efb9f1705c2cdd7efd8b712a3cba63ed7accedab40e432a85436546e5f66a6d258d0b39d5643d558fcf6cf1b05ca440699950a4973d3ade9e44e
    worker-1:     - SHA256:d4bc58c10ea5c99b12a8a780f594550f13e029a612b4fd3de8c2c34a565be7d7
    worker-1:     - SHA1:a83f7232c93cf0dc7c065ee40cc45b26804302f8 [weak]
    worker-1:     - MD5Sum:cb43954ad4829657da56cad4c98f5b4c [weak]
    worker-1:     - Filesize:22530546 [weak]
    worker-1:    Last modification reported: Tue, 23 Jun 2020 01:50:46 +0000
    worker-1: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by misbahulard** [comment]
@fekezue Which VirtualBox version do you use?
I'm using VirtualBox 6 it keeps crashing in Windows 10, then install VirtualBox 5 and it's work now.

**Comment by fireflycons** [comment]
Hi @fekezue  @misbahulard 

Please try our new upgraded version of this which is upgraded to 1.24. Since 1.24 no longer uses docker as the CRI, all the above has been removed - along with other bugs fixed.

Please try it now with latest virtualbox and vagrant, and feel free to raise further issues.

Thanks.
