### ISSUE TITLE
How do I stop / shutdown the cluster?

### ISSUE THREAD

**Issue by freephile** [mmumshad/kubernetes-the-hard-way#153]
I've gone through each of the lectures and successfully setup a cluster. However, I'm still very new to Kubernetes. How do I properly shut down the cluster?

**Comment by fireflycons** [comment]
Hi @freephile 

Clusters are pretty resilient. If you're looking for an order, then shut down the workers first then the control plane. You would not generally be stopping a production cluster unless you were taking it out of service following migration of workloads to a replacement cluster.
