### ISSUE TITLE
Lecture Request - CKA

### ISSUE THREAD

**Issue by tarunarora20** [mmumshad/kubernetes-the-hard-way#156]
Lecture Addition Request for CRD's, Operators, Stateful Sets and Admission Controllers

**Comment by fireflycons** [comment]
Hi @tarunarora20 

CRDs and Admission Controllers are covered by CKAD/CKS

You can raise requests for new courses by going to the following link. If something similar to what you're looking for is already present in the list, simply upvote it else add a new request.
Thanks.

https://kodekloud.com/request-a-course/
