### ISSUE TITLE
Worker node error> The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by oneitworld** [mmumshad/kubernetes-the-hard-way#158]
Hi, I am getting the following error in my worker-1 and worker-2 nodes, when trying to apply the following command>

vagrant@worker-2:~$ kubectl create -f auto-approve-csrs-for-group.yaml
The connection to the server localhost:8080 was refused - did you specify the right host or port?

That happened following the steps in lesson> 
https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/10-tls-bootstrapping-kubernetes-workers.md

Any help would be very much appreciated.. as I think I missed some step maybe prior lessons even though that before I have no errors on any applying instruction..

Best regards,

**Comment by deepakkt-a** [comment]
@oneitworld You need to run them on the master.

**Comment by bluelurker** [comment]
@deepakkt-a Thanks. @mmumshad Could you please update this in the guide?
It's not mentioned there.
https://github.com/mmumshad/kubernetes-the-hard-way/blob/a09cbf541fd3824f4d1cbd93878e63d3b4025d58/docs/10-tls-bootstrapping-kubernetes-workers.md

**Comment by fireflycons** [comment]
Hi @kaliavarun 

We don't set up a kubeconfig on the workers, as in a real-life scenario it should not be necessary to run kubectl commands from workers. Indeed it should not even be necessary to log into workers apart from troubleshooting.

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade, and the instructions on what to do from where should be clearer. Please try it now and feel free to raise further issues.

Thanks.
