### ISSUE TITLE
Issue with weave network configuration

### ISSUE THREAD

**Issue by raihanchdy** [mmumshad/kubernetes-the-hard-way#163]
I followed same doc. Nodes are discovered by the master also.
weave setup is not happening and kube-api is throwing error "http: TLS handshake error from, bad, remote error: tls: bad certificate"

Did anybody face the issue and able to fix?

**Comment by fireflycons** [comment]
Hi @raihanchdy 

You probably did not get the tls-bootstrapped worker to come up properly. 

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. Please try it now and feel free to raise further issues.

Thanks.
