### ISSUE TITLE
Geting permission denied (publickey) while sending out certificates 

### ISSUE THREAD

**Issue by fasiadel** [mmumshad/kubernetes-the-hard-way#165]
Error Permission denied (publickey) on master-1 created by vagrant

**Comment by fireflycons** [comment]
Hi @fasiadel 
What @Jay1305 did isn't a "fix", it is what you are supposed to do as part of the initial setup - that is, to create the ssh keys on `master-1` and distribute to the other master and the 2 workers, such that SCP operations later on can work.

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. Please try it now and feel free to raise further issues.

Thanks.
