### ISSUE TITLE
Lecture Request_CKA

### ISSUE THREAD

**Issue by akmani1987** [mmumshad/kubernetes-the-hard-way#166]
Please put a session on Helm charts and istio.
Second -- include a video to explain difference in certification b/w new and old sylabus,.

**Comment by mokua** [comment]
@akmani1987 - on the difference between old and new sylabus this can help
https://monicabhartiya.com/posts/kubernetes-syllabus-update

Kind regards,
Mokua

**Comment by fireflycons** [comment]
Hi @akmani1987 

Since Kubernetes 1.21 Helm is part of CKAD and is covered by our lectures.
We also have dedicated Helm and Istio courses at https://kodekloud.com
