### ISSUE TITLE
Restore options 

### ISSUE THREAD

**Issue by kalra80** [mmumshad/kubernetes-the-hard-way#167]
QQ - Why we used 127.0.0.1 instead of actual k8 cluster IPs ? I checked etcd.yaml of my cluster and it uses master server IP. Wondering if we can use the same IP or we have or use127.0.0.1 IP while restoring ETCD

**Comment by fireflycons** [comment]
Hi @kalra80 

Please see our FAQ here: https://github.com/kodekloudhub/community-faq/blob/main/etcd-faq.md

Thanks
