### ISSUE TITLE
incorrect   --runtime-config in apiserver systemd file 

### ISSUE THREAD

**Issue by mhamzeh** [mmumshad/kubernetes-the-hard-way#171]
under https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md

Configure the Kubernetes API Server
we are passing the following option to apiserver   --runtime-config=api/all \\, which is invalid as per documentation.
this option should be   --runtime-config=api/all=true \\

reference https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

**Comment by fireflycons** [comment]
Hi @mhamzeh 

We have now merged a major change to bring this to v1.24.
Many issues including this have been addressed as part of the upgrade. Please try it now and feel free to raise further issues.

Thanks.
