### ISSUE TITLE
There was an error while executing `VBoxManage`, a CLI used by Vagrant

### ISSUE THREAD

**Issue by holynakamoto** [mmumshad/kubernetes-the-hard-way#175]
Windows: 10 Build 20211
Vagrant: 2.2.10
Vbox: 6.1.14

Fix:

Navigate to "C:\Program Files\Oracle\VirtualBox\drivers\vboxdrv"
Right click on "VBoxDrv.inf" file and select Install option
Open the Console as a administrator and run the following command

sc start vboxdrv

**Comment by knrt10** [comment]
https://github.com/mmumshad/kubernetes-the-hard-way/issues/24#issuecomment-513637790

Also update to the latest version, that will fix the issue
