### ISSUE TITLE
HI @mmumshad  In the TLS certificate creation course. There is wrong certificate used in the kube Api server config file.....  Check for kubelet client certificates....  It is showing apiserver-etcd-client.crt

### ISSUE THREAD

**Issue by mmumshad** [mmumshad/kubernetes-the-hard-way#18]
HI @mmumshad  In the TLS certificate creation course. There is wrong certificate used in the kube Api server config file.....  Check for kubelet client certificates....  It is showing apiserver-etcd-client.crt

https://kodekloud.slack.com/archives/CHMV3P9NV/p1560943687161600?thread_ts=1560943687.161600&cid=CHMV3P9NV

**Comment by Tej-Singh-Rana** [comment]
This has been fixed. 
<img width="614" alt="image-769" src="https://user-images.githubusercontent.com/58101587/191975947-c22b7204-eeb2-4637-bff8-5a56675b0223.png">
