### ISSUE TITLE
Can anyone help

### ISSUE THREAD

**Issue by dhikrahashim** [mmumshad/kubernetes-the-hard-way#185]
I am getting below error when i check the kubelet status

Oct 18 08:14:06 node-1 kubelet[18942]: E1018 08:14:06.025167   18942 reflector.go:127] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.RuntimeClass: failed to list *v1beta1.RuntimeClass: Get "https://10.142.0.2:6443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0": x509: certificate signed by unknown authority

Oct 18 08:14:26 node-1 kubelet[18942]: E1018 08:14:26.984736   18942 eviction_manager.go:260] eviction manager: failed to get summary stats: failed to get node info: node "node-1" not found

IP: 10.142.0.2 is my haproxy loadbalancer

This issue came after first node setup. Do we need certificate in LB server also ?

**Comment by fireflycons** [comment]
Hi @dhikrahashim 

The LB does not require a cert. It's set up as a layer 4 (network) load balancer, therefore it operates at TCP level and ignores SSL. The requests are forwarded unchanged to the API server, and that deals with the SSL.

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. Please try it now and feel free to raise further issues.

Thanks.
