### ISSUE TITLE
check-etcd failed while high availability cluster configuration on your vagrant config

### ISSUE THREAD

**Issue by arkeyme** [mmumshad/kubernetes-the-hard-way#189]
There is an issue with high availability cluster configuration on your vagrant config. At first you may get this issue while adding additional master nodes to the cluster:

```
[kubeconfig] Generating kubeconfig files
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[check-etcd] Checking that the etcd cluster is healthy
error execution phase check-etcd: error syncing endpoints with etcd: context deadline exceeded
To see the stack trace of this error execute with --v=5 or higher
```

To overcome this issue you should execute command to init this cluster with this flag `--apiserver-advertise-address=192.168.5.11` for example:

`sudo kubeadm init --control-plane-endpoint "lb:6443" --upload-certs --apiserver-advertise-address=192.168.5.11 --pod-network-cidr="172.19.0.0/16" --service-cidr="10.96.0.0/16"`

As for another master nodes this command should be:

```
#master-2:
sudo kubeadm join lb:6443 --apiserver-advertise-address=192.168.5.12 --token ech...tc \
    --discovery-token-ca-cert-hash sha256:a4...dea \
    --control-plane --certificate-key 2b...94
#master-3:
sudo kubeadm join lb:6443 --apiserver-advertise-address=192.168.5.13 --token ech...tc \
    --discovery-token-ca-cert-hash sha256:a4...dea \
    --control-plane --certificate-key 2b...94
```
The root cause of the issue is vagrant NICs configuration, by default kube-apiserver listens NIC which virtual box uses to forward traffic to NAT

**Comment by fireflycons** [comment]
Hi @arkeyme 

Is this still incorrect in the course? If so, please raise in the community forums
https://community.kodekloud.com/

Thanks
