### ISSUE TITLE
 mmumshad / kubernetes-the-hard-way apiserver argument runtime-config value is invalid

### ISSUE THREAD

**Issue by sonogithub** [mmumshad/kubernetes-the-hard-way#191]
Referring to

https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md
amongst the arguments to apiserver it has
"..
--runtime-config=api/all \\
"

This is literally invalid.
Refer to the api server documentation
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
it describes the valid values for this optional argument:
"--runtime-config mapStringString
	A set of key=value pairs that enable or disable built-in APIs. Supported options are:
v1=true|false for the core API group
<group>/<version>=true|false for a specific API group and version (e.g. apps/v1=true)
api/all=true|false controls all API versions
api/ga=true|false controls all API versions of the form v[0-9]+
api/beta=true|false controls all API versions of the form v[0-9]+beta[0-9]+
api/alpha=true|false controls all API versions of the form v[0-9]+alpha[0-9]+
api/legacy is deprecated, and will be removed in a future version
"

I believe this case the intention would be achieved by correcting this argument/value to read

--runtime-config=api/all=true

**Comment by fireflycons** [comment]
Hi @sonogithub

That was eventually corrected, however we have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. Please try it now and feel free to raise further issues.

Thanks.
