### ISSUE TITLE
Helm and Helm Charts - Lecture Request

### ISSUE THREAD

**Issue by thiagu89** [mmumshad/kubernetes-the-hard-way#192]
Request to have topics on Helm and Helm Charts #CKAD #Lecture Request

**Comment by gunnykc** [comment]
But helm is not a part of the CKAD or CKA exam. He must definitely come up with a new course. Hoping to get it from KodKloud.

**Comment by fireflycons** [comment]
Hi @thiagu89 

Since Kubernetes 1.21 Helm is part of CKAD and is covered by our lectures.
We also have a dedicated Helm course at https://kodekloud.com
