### ISSUE TITLE
Lecture Request CKA

### ISSUE THREAD

**Issue by shital-pawar-dc** [mmumshad/kubernetes-the-hard-way#196]
Please add helm chart and helm value lectures

**Comment by gunnykc** [comment]
But helm is not a part of the CKAD or CKA exam. He must definitely come up with a new course. Hoping to get it from KodKloud.

**Comment by fireflycons** [comment]
Hi @shital-pawar-dc 

Since kubernetes 1.21 Helm is part of CKAD and is covered by our lectures.
