### ISSUE TITLE
"Lecture Request" and "CKA"

### ISSUE THREAD

**Issue by vidyasagarreddyc** [mmumshad/kubernetes-the-hard-way#200]
Auto scaling a cluster

Horizontal POD autoscalers

Stateful Sets

Kubernetes Federation

Admission Controllers

**Comment by fireflycons** [comment]
Hi @vidyasagarreddyc 

Admission controllers are covered in CKAD and CKS. They are not part of curriculum for CKA.

You can raise requests for new courses by going to the following link. If something similar to what you're looking for is already present in the list, simply upvote it else add a new request.
Thanks.

https://kodekloud.com/request-a-course/
