### ISSUE TITLE
"Lecture Request for Helm chart"

### ISSUE THREAD

**Issue by vidyasagarreddyc** [mmumshad/kubernetes-the-hard-way#201]

**Comment by gunnykc** [comment]
But helm is not a part of the CKAD or CKA exam. He must definitely come up with a new course. Hoping to get it from KodKloud.

**Comment by fireflycons** [comment]
Hi @vidyasagarreddyc 

Since kubernetes 1.21, Helm is part of CKAD. It is covered by our CKAD lectures.
