### ISSUE TITLE
Issue in deploying weave network -- Unable to connect to the server: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by sukhesh01** [mmumshad/kubernetes-the-hard-way#207]
I have issues in deploying the weave network. I get the below error message while running kubectl apply command

root@master-1:/etc/sysctl.d# kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

Unable to connect to the server: x509: certificate signed by unknown authority

I am following the kubernetes-the-hard-way document and stuck here.

**Comment by p3g2or** [comment]
I have the same issue.
Maybe the configuration of worker-2 node is not complete in the documentation?
Or did we miss something?

**Comment by forexstudies** [comment]
you did not miss anything
i can to the same error as well. and I am having problems fixing this

**Comment by amazingandyyy** [comment]
same issue +1

**Comment by zeeveisenberg** [comment]
I have the same error as well. I think this lab needs to be updated to support more current versions of k8s. It needs to properly support 1.20. In addition, there are a number of small errors, omissions, etc in the different steps (like not mentioning that you have to turn off swapping on the worker nodes or kubelet will not run). It's a great tutorial but badly needs to be revised and updated for the newer k8s versions.

**Comment by johncleveland** [comment]
I do not have the problem with the weave-network, but I do have the certificate signed by unknown authority error when I try to read the logs or use exec e.g. 15-smoke-test.md. It must be a problem with TLS bootstrapping because worker-node 1 works which was configured manually works fine.

**Comment by fireflycons** [comment]
Hi @sukhesh01 @amazingandyyy @p3g2or @johncleveland @forexstudies @zeeveisenberg 

The problem will be that you didn't get the tls-bootstrapped node up correctly. The kubelet will self-sign if it does not correctly negotiate with the cluster.

We have now merged a major change to bring this to v1.24.
Please try it now and feel free to raise further issues.

Thanks.
