### ISSUE TITLE
Rancher pods report error syncing 'fleet'

### ISSUE THREAD

**Issue by agvaliente** [mmumshad/kubernetes-the-hard-way#209]
Hello

I have installed rancher rancher-2.5.5 on kubernetes 1.19, the pods ranchr is reporting this error:

[ERROR] error syncing 'fleet': handler mcm-start: error running the jail command: exit status 2, requeuing

The option used was:

helm install rancher rancher-stable/rancher \
  --namespace cattle-system \
  --set hostname=rancher.ptmindra.net \
  --set ingress.tls.source=secret

**Comment by fireflycons** [comment]
Hi @agvaliente 

For questions about Rancher, the best place to ask is https://forums.rancher.com/
Thanks.
