### ISSUE TITLE
Lecture Request and CKA

### ISSUE THREAD

**Issue by code-scavenger-007** [mmumshad/kubernetes-the-hard-way#211]
Hi Mumshad,

Could you please add kubeless section on this course. 
Its similar to AWS lambdas functions and azure function.
It will be great learning if you can add this topic in depth.

**Comment by fireflycons** [comment]
Hi @code-scavenger-007 

This topic isn't part of the CKA curriculum so wouldn't be added to the lectures.

You can raise requests for new courses by going to the following link. If something similar to what you're looking for is already present in the list, simply upvote it else add a new request.
Thanks.

https://kodekloud.com/request-a-course/
