### ISSUE TITLE
CKA Lecture Request: Adding support for integration with Clouds (ex: Azure - Kubernetes on Azure) 

### ISSUE THREAD

**Issue by joslat** [mmumshad/kubernetes-the-hard-way#212]
It would be great that the cloud integration with Kubernetes is covered in the course.

Thank you for the outstanding course!

Cheers,
José

**Comment by fireflycons** [comment]
Hi @joslat 

Cloud integration is not part of the curriculum for CKA, so wouldn't be covered by the lectures.

You can raise requests for new courses by going to the following link. If something similar to what you're looking for is already present in the list, simply upvote it else add a new request.
Thanks.

https://kodekloud.com/request-a-course/
