### ISSUE TITLE
Lecture Request - CKA

### ISSUE THREAD

**Issue by samrat157** [mmumshad/kubernetes-the-hard-way#215]
Helm Packaging

**Comment by gunnykc** [comment]
But helm is not a part of the CKAD or CKA exam. He must definitely come up with a new course. Hoping to get it from KodKloud.

**Comment by fireflycons** [comment]
Hi @samrat157 

Since Kubernetes 1.21 Helm is part of CKAD and is covered by our lectures.

We have a separate course dedicated to Helm at https://kodekloud.com
