### ISSUE TITLE
Issue on step 13 during kubernetes set up hardway

### ISSUE THREAD

**Issue by kumarvmadhu** [mmumshad/kubernetes-the-hard-way#217]
Getting below error though the steps followed as suggested. Please assist
![Capture](https://user-images.githubusercontent.com/83343562/116784316-371fa780-aac6-11eb-9a15-4566187bde10.JPG)

**Comment by mustafaerbay** [comment]
I also got the same error message, I follow below commands;

**Comment by fireflycons** [comment]
Hi @mustafaerbay @kumarvmadhu 

We have now merged a major change to bring this to v1.24.
This has been addressed as part of the upgrade. Please try it now and feel free to raise further issues.

Thanks.
