### ISSUE TITLE
encryption config copy issue

### ISSUE THREAD

**Issue by smrutimandal** [mmumshad/kubernetes-the-hard-way#218]
The movement of encryption-config.yaml shouldn't be done at https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/06-data-encryption-keys.md#the-encryption-config-file for two reasons:

1. /var/lib/kubernetes doesn't exist yet.
2. The copying is being done at https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md#configure-the-kubernetes-api-server

**Comment by fireflycons** [comment]
Hi @smrutimandal 

We have now merged a major change to bring this to v1.24.
This has been addressed as part of the upgrade. Please try it now and feel free to raise further issues.

Thanks.
