### ISSUE TITLE
[FEATURE REQUEST] Add cert check for Worker-2

### ISSUE THREAD

**Issue by smrutimandal** [mmumshad/kubernetes-the-hard-way#220]
Hi,

Great work! Thanks for sharring.

Could you please add certificate checks for worker-2 validating the kube-apiserver and kubelet authentication as well.

Thanks.

**Comment by fireflycons** [comment]
Hi @smrutimandal 

We have now merged a major change to bring this to v1.24.
This has been addressed as part of the upgrade, and the documentation invites you to run `cert_verify.sh` at various stages of the deployment. Please try it now and feel free to raise further issues.

Thanks.
