### ISSUE TITLE
service account token is already expired

### ISSUE THREAD

**Issue by shashikn123** [mmumshad/kubernetes-the-hard-way#229]
The service token created in the chapter 10: TLS bootstrapping has an expiry date which is a past date. This causes the kubelet's authentication to fail against kube-apiserver

**Comment by willcoderwang** [comment]
Thanks for pointing this out. You saved my day.

**Comment by fireflycons** [comment]
Hi @shashikn123  @willcoderwang 

We have now merged a major change to bring this to v1.24.
This has been addressed as part of the upgrade - the token expiry is now calculated to a shell variable as "7 days from now", and the variable used in the manifest. Please try it now and feel free to raise further issues.

Thanks.
