### ISSUE TITLE
Wrong API user is defined - 13-kube-apiserver-to-kubelet

### ISSUE THREAD

**Issue by shashikn123** [mmumshad/kubernetes-the-hard-way#230]
Hello,

I see the user to which we are binding the ClusterRole 'system:kube-apiserver-to-kubelet' is 'system:kube-apiserver'. But the user defined in the '--kubelet-client-certificate' of API server is different i.e 'kube-apiserver'. This is the user for which the certificate was generated in the earlier lectures. 

This causes the API server authorization to kubelet fail while running 'kubectl exec' against any pods. 

vagrant@master-1:~$ kubectl exec -ti busybox -- nslookup kubernetes
error: unable to upgrade connection: Forbidden (user=kube-apiserver, verb=create, resource=nodes, subresource=proxy)
vagrant@master-1:~$

Please update the document to update the correct user in the clusterrolebindings.

**Comment by kareotoko** [comment]
> Hello,
> 
> I see the user to which we are binding the ClusterRole 'system:kube-apiserver-to-kubelet' is 'system:kube-apiserver'. But the user defined in the '--kubelet-client-certificate' of API server is different i.e 'kube-apiserver'. This is the user for which the certificate was generated in the earlier lectures.
> 
> This causes the API server authorization to kubelet fail while running 'kubectl exec' against any pods.
> 
> vagrant@master-1:~$ kubectl exec -ti busybox -- nslookup kubernetes error: unable to upgrade connection: Forbidden (user=kube-apiserver, verb=create, resource=nodes, subresource=proxy) vagrant@master-1:~$
> 
> Please update the document to update the correct user in the clusterrolebindings.

Thanks, but If I want to keep the name of user in "13-kube-apiserver-to-kubelet.md" as it is. Which part should I change in earlier lectures so it will be similar with the name in -13-kube-apiserver-to-kubelet.md- if I want to start over from beginning?

**Comment by fireflycons** [comment]
Hi @kareotoko 

We have now merged a major change to bring this to v1.24.
This has been addressed as part of the upgrade. Please try it now and feel free to raise further issues if you find them.
