### ISSUE TITLE
Lecture Request CKAD

### ISSUE THREAD

**Issue by bschaitanya91** [mmumshad/kubernetes-the-hard-way#232]
Could you please also add Helm, I have been attending interviews and so many were asking about Helm. If you could add helm it would be much appreciable.

**Comment by gunnykc** [comment]
But helm is not a part of the CKAD or CKA exam. He must definitely come up with a new course. Hoping to get it from KodKloud.

**Comment by sriramnambi** [comment]
Helm is a part of upcoming CKAD 2021 curriculum. SO it will be nice to have that.

**Comment by M-Ayman** [comment]
Also, you can submit a request here https://kodekloud.com/p/request-a-course
