### ISSUE TITLE
"Lecture Request" "CKA"

### ISSUE THREAD

**Issue by goochaan** [mmumshad/kubernetes-the-hard-way#233]
Could you please add HELM to your CKA course.

"Lecture Request" "CKA"

**Comment by gunnykc** [comment]
But helm is not a part of the CKAD or CKA exam. He must definitely come up with a new course. Hoping to get it from KodKloud.

**Comment by addastane** [comment]
Yes I am searching for the same too. (Helm)

**Comment by RushabhMavaniTR** [comment]
Yes,, Helm and Istio

**Comment by fireflycons** [comment]
Hi @gunnykc @goochaan 

Since Kubernetes 1.21, Helm is part of CKAD and is covered by our lectures.
We also have dedicated courses for helm and istio at https://kodekloud.com
