### ISSUE TITLE
Any topic on kubernetes operator development and lifecycle

### ISSUE THREAD

**Issue by addastane** [mmumshad/kubernetes-the-hard-way#235]
Just an advice on following topic.
kubernetes operator development and lifecycle, CustomResource.

**Comment by rid3thespiral** [comment]
yes, i think that CRD are needed also for the new CKAD exam curriculum

**Comment by katehooper89** [comment]
I hope this post will be useful for people who wants to take next step in their career and **Pass Linux Foundation CKAD Exam** certification. The range of knowledge as you can see is wide and sometimes you need to know the details, but this **Pdfcerts** will make you a better specialist and will open more opportunities in front of you. I hope you pass Linux Foundation CKAD exam dumps and find your name under **Linux Foundation Kubernetes Application Developer** Certified Kubernetes Application Developer Exam!

**Download Full Practice Exam Material Here:** https://www.pdfcerts.com/Linux Foundation/CKAD-exam-questions.html

**Comment by fireflycons** [comment]
Hi @rid3thespiral @addastane 

It is correct that CKAD touches on operators, so there are now a couple of lectures on this in our course. They do not go into details about how to create an operator, only how you create CRDs, deploy operators and their use cases.
There are plenty of articles in places like Medium where people discuss how to build a basic operator in Python or Golang.

Thanks.
