### ISSUE TITLE
"Lecture Request" "CKA"

### ISSUE THREAD

**Issue by dpinara** [mmumshad/kubernetes-the-hard-way#238]
Can you please add Kustomize topic. In any enterprise world , we don't see using kubernetes application without using Kustomize ( or any similar optioln). Using your course Mumshad, I have cleared CKAD and now pursuing CKA. However knowledge gained while preparing CKA or CKAD,  its still lacking in organization - real world !!. Kustomize is not something one can not learn, however i feel that it is missing part in exam as well as in course you have prepared accrodingly. Afterall in enterprise world, who will use kubectl run to create pod :) 

Cheers
Dhaval

**Comment by M-Ayman** [comment]
you can submit your request here https://kodekloud.com/p/request-a-course

**Comment by jhoni89** [comment]
Hi, 
I have purchase and **pass Linux Foundation CKA exam with 50% discount** limited time offer Yet...i suggest and help you can also get Any Linux Foundation Certifications Practice Guide From Here This Link:

**Download Full Practice Exam Material Here**: https://www.validexamdumps.com/linux-foundation/cka-dumps
