### ISSUE TITLE
"Lecture Request" "CKA"

### ISSUE THREAD

**Issue by Abisaha** [mmumshad/kubernetes-the-hard-way#240]
Auto scaling a cluster

Horizontal POD autoscalers

Stateful Sets

Kubernetes Federation

Admission Controllers

**Comment by katehooper89** [comment]
I hope this post will be useful for people who wants to take next step in their career and **Pass Linux Foundation CKA Exam certification**. The range of knowledge as you can see is wide and sometimes you need to know the details, but this **Pdfcerts** will make you a better specialist and will open more opportunities in front of you. I hope you pass **Linux Foundation CKA exam** dumps and find your name under Linux Foundation Kubernetes Administrator Certified Kubernetes Administrator Exam!

**Download Full Practice Exam Material Here:** https://www.pdfcerts.com/Linux Foundation/CKA-exam-questions.html

**Comment by fireflycons** [comment]
Hi @Abisaha 

With the exception of Admission Controllers, which appear in existing CKAD and CKS courses, the others are not requirements for the exams.

Please raise requests for new lectures/courses by going to the following link. If something similar to what you're looking for is already present in the list, simply upvote it else add a new request.
Thanks.

https://kodekloud.com/request-a-course/
