### ISSUE TITLE
Core DNS is not able to create pods

### ISSUE THREAD

**Issue by lakshmiprasad2019** [mmumshad/kubernetes-the-hard-way#242]
I have completed cluster configuration using hard-way method but I am getting issue at last while applying core DNS.

Getting below error.

vagrant@master-1:~$ kubectl get pods -n kube-system
NAME                       READY   STATUS              RESTARTS   AGE
**coredns-69cbb76ff8-94x59   0/1     ContainerCreating   0          25s
coredns-69cbb76ff8-tkd9k   0/1     ContainerCreating   0          24m**
weave-net-p54jv            2/2     Running             1          39m
weave-net-rlhjl            2/2     Running             1          39m

Bove pods are not getting create and when I see the logs getting below error.

Events:
  Type     Reason                  Age                  From               Message
  ----     ------                  ----                 ----               -------
  Normal   Scheduled               2m51s                default-scheduler  Successfully assigned kube-system/coredns-69cbb76ff8-hq79w to worker-1
  Warning  FailedCreatePodSandBox  2m42s                kubelet, worker-1  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "54593dffc8c5447186c19e2a349789d214bdff220392f4fce577906abf77eedd" network for pod "coredns-69cbb76ff8-hq79w": NetworkPlugin cni failed to set up pod "coredns-69cbb76ff8-hq79w_kube-system" network: **failed to find plugin "loopback" in path [/opt/cni/bin], failed to clean up sandbox container** "54593dffc8c5447186c19e2a349789d214bdff220392f4fce577906abf77eedd" network for pod "coredns-69cbb76ff8-hq79w": NetworkPlugin cni failed to teardown pod "coredns-69cbb76ff8-hq79w_kube-system" n**etwork: failed to find plugin "portmap" in path [/opt/cni/bin]]**
  Normal   SandboxChanged          0s (x14 over 2m42s)  kubelet, worker-1  Pod sandbox changed, it will be killed and re-created.

Please help me to fix this issue,

**Comment by lakshmiprasad2019** [comment]
Getting same issue for all deployments.  I tried to create one more deployment with other image,  But still same error.

Events:
  Type     Reason                  Age                     From               Message
  ----     ------                  ----                    ----               -------
  Normal   Scheduled               22s                     default-scheduler  Successfully assigned default/nginx-5c7588df-dtk7s to worker-2
  Warning  FailedCreatePodSandBox  9s                      kubelet, worker-2  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "5ecc684ca1c23fa96539266546153f118382e42d0a5d679019c3bbbc7c477b01" network for pod "nginx-5c7588df-dtk7s": NetworkPlugin cni failed to set up pod "nginx-5c7588df-dtk7s_default" network: failed to find plugin "loopback" in path [/opt/cni/bin], failed to clean up sandbox container "5ecc684ca1c23fa96539266546153f118382e42d0a5d679019c3bbbc7c477b01" network for pod "nginx-5c7588df-dtk7s": NetworkPlugin cni failed to teardown pod "nginx-5c7588df-dtk7s_default" network: failed to find plugin "portmap" in path [/opt/cni/bin]]
  Normal   SandboxChanged          <invalid> (x2 over 8s)  kubelet, worker-2  Pod sandbox changed, it will be killed and re-created.

**Comment by fireflycons** [comment]
Hi @lakshmiprasad2019 
Looks like you might have missed a small step somewhere. However,  we have now merged a major change to bring this to v1.24.
Please try it now and feel free to raise further issues.

Thanks.
