### ISSUE TITLE
Unhealthy components 

### ISSUE THREAD

**Issue by movinglightspeed** [mmumshad/kubernetes-the-hard-way#243]
kubectl get cs
NAME                 STATUS      MESSAGE                                                                                     ERROR
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused
etcd-0               Healthy     {"health":"true"}
etcd-1               Healthy     {"health":"true"}

I am stuck on Bootstrapping kubernetes controllers 
I am on https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md

**Comment by fireflycons** [comment]
Hi @movinglightspeed 

We have now merged a major change to bring this to v1.24. Please try again and be sure to carefully follow each step in order and from the correct hosts. We have thoroughly tested this release.

Thanks
