### ISSUE TITLE
Lecture Request CKA 

### ISSUE THREAD

**Issue by sohaib2k4** [mmumshad/kubernetes-the-hard-way#246]
ArgoCD
kubernetes via terraform
Istio

**Comment by fireflycons** [comment]
Hi @sohaib2k4 

Please raise requests for lectures/courses by going to the following link. If something similar to what you're looking for is already present in the list, simply upvote it else add a new request.

We do now have an Istio course on our platform. An Argo course is scheduled.

Thanks.

https://kodekloud.com/request-a-course/
