### ISSUE TITLE
Lecture Request

### ISSUE THREAD

**Issue by udautkarsh** [mmumshad/kubernetes-the-hard-way#250]
NFV Features in kubernetes, like SR-IOV, DPDK etc

**Comment by fireflycons** [comment]
Hi @udautkarsh 

These are outside the scope of CKA/CKAD/CKS, however you can request a course by going to the following link. If something similar to what you're looking for is already present in the list, simply upvote it else add a new request.
Thanks.

https://kodekloud.com/request-a-course/
