### ISSUE TITLE
Errors while setup

### ISSUE THREAD

**Issue by manpreetiitm** [mmumshad/kubernetes-the-hard-way#261]
master-1:~#  kubectl get componentstatuses --kubeconfig admin.kubeconfig
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?

**Comment by tarikly** [comment]
After --kubeconfig try to pass the full path to kubeconfig file.

**Comment by fireflycons** [comment]
Hi @manpreetiitm 

We have now merged a major change to bring this to v1.24, including several bug fixes. Please try again and raise a new issue for any issues found.

Thanks.
