### ISSUE TITLE
Link to Slack group in Udemy course is invalid

### ISSUE THREAD

**Issue by linuxhistoryblg** [mmumshad/kubernetes-the-hard-way#262]
In the course:
    Kubernetes Certified Application Developer (CKAD) with Tests
In the section: 
    Section 1 - Introduction
On page:
    Number 7 : Join our Slack group
The link to the Slack group:
    https://join.slack.com/t/kodekloud/shared_invite/zt-zjqp39qb-c5krtK6tJ0f8kinPOg34IQ
Returns the error:
    This link is no longer active To join this workspace, you’ll need to ask the person who originally invited you for a new link.

**Comment by tarikly** [comment]
try: https://kodekloud.slack.com/

**Comment by fireflycons** [comment]
Hi @linuxhistoryblg 

If you are still having issues, please reach out to support@kodekloud.com
