### ISSUE TITLE
Can we have a Hands on lab or Test environment to convert a monolithic app to docker image?

### ISSUE THREAD

**Issue by gokul2018** [mmumshad/kubernetes-the-hard-way#277]
Hi Team,

While all the concepts are clearly explained, to be job ready, can we have some hands on lab or some sample apps which are monolithic running on .Net or .Net core and show us how to convert it into a app that runs on K8s?

**Comment by fireflycons** [comment]
Hi @gokul2018 


You can raise requests for new courses by going to the following link. If something similar to what you're looking for is already present in the list, simply upvote it else add a new request.
Thanks.

https://kodekloud.com/request-a-course/
