### ISSUE TITLE
Running commands in parallel with tmux

### ISSUE THREAD

**Issue by bradotlin** [mmumshad/kubernetes-the-hard-way#278]
On page https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md in the "Running commands in parallel with tmux" section it says "See the [Running commands in parallel with tmux](https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/01-prerequisites.md#running-commands-in-parallel-with-tmux) section in the Prerequisites lab". But on https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/01-prerequisites.md I do not see anything about tmux or running commands in parallel.

**Comment by fireflycons** [comment]
Hi @bradotlin 

We have now merged a major change to bring this to v1.24.
This has been addressed as part of the upgrade. Please try it now and feel free to raise further issues.
