### ISSUE TITLE
Copy certificates, private keys and kubeconfig files to the worker node

### ISSUE THREAD

**Issue by bradotlin** [mmumshad/kubernetes-the-hard-way#279]
On https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/09-bootstrapping-kubernetes-workers.md#copy-certificates-private-keys-and-kubeconfig-files-to-the-worker-node

### **Copy certificates, private keys and kubeconfig files to the worker node**:
On master-1:

the command is displayed as: 
`master-1$ scp ca.crt worker-1.crt worker-1.key worker-1.kubeconfig worker-1:~/`

but should be
`scp ca.crt worker-1.crt worker-1.key worker-1.kubeconfig worker-1:~/`

Also, on the same page many "worker-1" commands have "worker-1$" in the code sections which makes copy/paste difficult

**Comment by fireflycons** [comment]
Hi @bradotlin 

We have now merged a major change to bring this to v1.24.
This has been addressed as part of the upgrade. Please try it now and feel free to raise further issues.
