### ISSUE TITLE
"Lecture Request" and "CKA" - CNI with calico

### ISSUE THREAD

**Issue by challamani** [mmumshad/kubernetes-the-hard-way#280]
Can you try cover Calico architecture and virtual IP address allocations to each pod, and performance advantages.

**Comment by fireflycons** [comment]
Hi @challamani 

Please raise requests for lectures/courses by going to the following link. If something similar to what you're looking for is already present in the list, simply upvote it else add a new request.

Thanks.

https://kodekloud.com/request-a-course/
