### ISSUE TITLE
kubelet / kube-proxy not starting.

### ISSUE THREAD

**Issue by tsaraujobr** [mmumshad/kubernetes-the-hard-way#281]
I have configured all the steps up to the topic Start Worker Services.
But, the kubelet and kube-proxy services do not start.
![image](https://user-images.githubusercontent.com/68303494/169713082-43b089d7-a3c8-47b0-a929-c67ff314a497.png)

Here is the error in syslog.
![image](https://user-images.githubusercontent.com/68303494/169713576-16056f19-98ee-4e42-b392-8057e0ae4d33.png)

![image](https://user-images.githubusercontent.com/68303494/169713634-3fe5c0ab-7abb-4305-8c1f-83e76aed3952.png)

This is Variable declared.
![image](https://user-images.githubusercontent.com/68303494/169713649-0e135770-6a6a-4103-8af6-1ef38734a441.png)

i don't know why this happening.
Can anyone help me?

**Comment by tsaraujobr** [comment]
Hi Everyone, 

I don't find any solution.
I would really like to finish this lab.
I don't know how to continue.

@mmumshad 
Do you know what could be happening?

**Comment by tsaraujobr** [comment]
kubelet.service
![image](https://user-images.githubusercontent.com/68303494/170037072-d9a2208d-a5fa-4671-b628-8612f3ae5eff.png)

kube-proxy.service
![image](https://user-images.githubusercontent.com/68303494/170037170-730b7a1b-c8ae-4cfa-8a7a-024480feec2b.png)

/var/lib/kubelet/worker-1.kubeconfig
![image](https://user-images.githubusercontent.com/68303494/170037749-4e0cdb66-3cad-4694-89a6-60933dc8c7a4.png)

/var/lib/kubelet/kubeconfig 
![image](https://user-images.githubusercontent.com/68303494/170037932-1dbe3dd1-371a-459f-bf58-2b304cd4c9f7.png)

/var/lib/kube-proxy/kube-proxy.kubeconfig
![image](https://user-images.githubusercontent.com/68303494/170037932-1dbe3dd1-371a-459f-bf58-2b304cd4c9f7.png)

/var/lib/kube-proxy/kube-proxy-config.yaml
![image](https://user-images.githubusercontent.com/68303494/170038099-7538edee-b0b3-4efb-bc66-678f326f3505.png)

**Comment by fireflycons** [comment]
Hi @tsaraujobr 

We have now merged a major change to bring this to v1.24.
This has been addressed as part of the upgrade. Please try it now and feel free to raise further issues.
