### ISSUE TITLE
Ip Range Issue 

### ISSUE THREAD

**Issue by mykefon** [mmumshad/kubernetes-the-hard-way#282]
I keep getting the error " The IP address configured for the host-only network is not within the
allowed ranges. Please update the address used to be within the allowed
ranges and run the command again.
 Address: 192.168.5.11 
 Ranges: 192.168.56.0/21. "

It manages to partially create 1 master node.

<img width="526" alt="Screen Shot 2022-06-03 at 3 32 12 PM" src="https://user-images.githubusercontent.com/100591000/171937130-105af480-1d7b-4959-9cbe-c30e88976525.png">

**Comment by vherzog** [comment]
@mykefon I ran into this as well (on MacOS Big Sur). What worked for me is changing the `IP_NW` in the Vagrantfile to `"192.168.56."`. Found this thread -> https://stackoverflow.com/questions/70704093/the-ip-address-configured-for-the-host-only-network-is-not-within-the-allowed-ra

**Comment by mykefon** [comment]
> Hi @mykefon, what is your operating system? Are you using vagrant in WSL2?

**Comment by mykefon** [comment]
@m18unet I used VSCode on MacOS Monterey.

**Comment by mykefon** [comment]
@vherzog I'll try that...Thanks!

**Comment by Jay1305** [comment]
Just started looking to this guide. Thank you!

![image](https://user-images.githubusercontent.com/31636584/182730206-88d697dc-6c8d-49a4-bbbd-778f5dbf8f56.png)

![image](https://user-images.githubusercontent.com/31636584/182730268-eaa8367a-375c-497a-b782-03d5983a1d76.png)

Workaround given by @vherzog is working!

**Comment by fireflycons** [comment]
Hi, 

We are shortly going to release an updated version to kubernetes 1.24. With this upgrade we are including instructions to easily set the host network range to suit individual requirements, and the default network will be `192.168.56`

Please check back in a couple of weeks.

Thanks
