### ISSUE TITLE
08 Bootstrapping the Kubernetes Control Plane problem

### ISSUE THREAD

**Issue by stuninslave** [mmumshad/kubernetes-the-hard-way#284]
Hello!
Going through the documentation step-by-step i get an error while bootstraping control plane.
I've checked myself and reproduce the issue twice.

kube-scheduler and kube-controll-manager status is Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused .

Using virtualbox +vagrant on windows 11 .
Get an error in verification:
![image](https://user-images.githubusercontent.com/31645483/174267684-95479c6f-0390-4ae3-b12b-1d04645580ab.png)

Kubectl
![image](https://user-images.githubusercontent.com/31645483/174267775-9f561e67-1dcd-41fa-bfa8-e6c812b7745c.png)

uname -a 

![image](https://user-images.githubusercontent.com/31645483/174267841-e641d313-f6bd-4fd3-8bba-2d99a72a3836.png)

kube-scheduller config

![image](https://user-images.githubusercontent.com/31645483/174267959-13cf633e-d861-471e-93d7-565a40de045f.png)

Encryption config
![image](https://user-images.githubusercontent.com/31645483/174268337-f2aaa232-dd08-4c45-b8df-b13c28522ccc.png)

Controll manager config
![image](https://user-images.githubusercontent.com/31645483/174268416-8752b0fa-f910-4f0a-bc25-b44eb94a6dd1.png)

systemctl
![image](https://user-images.githubusercontent.com/31645483/174268488-7d0312c1-9322-4be7-a8f1-b7d399151ad3.png)

**Comment by stuninslave** [comment]
:<

**Comment by albertriu98** [comment]
It happens the same to me

**Comment by Farshid1723** [comment]
Hi @albertriu98 , Have you been able to fix the issue? I am stuck with the same issue here.

**Comment by stuninslave** [comment]
Hello @Farshid1723, unfortunately, no. I've skipped this installation, and just bought kodekloud subscribition to learn kubernetes instead.

**Comment by fireflycons** [comment]
Hi @stuninslave @Farshid1723 @albertriu98 
Yesterday we merged a major update to bring this to v1.24 including many bug fixes.
Please try it now.
