### ISSUE TITLE
Getting SSL issue while executing the vagrant scripts

### ISSUE THREAD

**Issue by sumitgaur26** [mmumshad/kubernetes-the-hard-way#286]
Hi,
I am getting the below error while script provisioning the worker node.
![image](https://user-images.githubusercontent.com/51076687/178992189-3cc689c5-5cef-4be7-9763-d179816224b1.png)

**Comment by fireflycons** [comment]
Hi @sumitgaur26 

We are shortly going to release an update of this to kubernetes 1.24, and the section you have reported the issue in has been completely rewritten.  

Check back in a couple of weeks and try the updated version. 

Thanks
