### ISSUE TITLE
Lecture Request and CKA

### ISSUE THREAD

**Issue by smathankar** [mmumshad/kubernetes-the-hard-way#287]
Please add autoscalling lectures

**Comment by fireflycons** [comment]
Hi @smathankar 

At present, neither cluster autoscaling nor horizontal pod autoscaling are within the scope of CKA, so would not be added to the lectures.

You can request a specific course by going to https://kodekloud.com/request-a-course/

First please check the list to see if somebody else has requested similar and upvote if you find it, else add a new request.

Thanks
