### ISSUE TITLE
I'd like to see "How to create and use Operators" covered in the CKA exam

### ISSUE THREAD

**Issue by Akintola** [mmumshad/kubernetes-the-hard-way#297]

**Comment by fireflycons** [comment]
Hi @Akintola 

The place to discuss the courses is https://kodekloud.com/community/c/kubernetes/6

However, the detail of managing operators isn't in the scope of the CKA exam, so would not be added to it. You can however request additional courses by going to https://kodekloud.com/request-a-course/

Search through the list to see if something similar is already requested. If so, simply upvote it. If not, then add it

Thanks
