### ISSUE TITLE
Mastering Kubernettes in GKE

### ISSUE THREAD

**Issue by Mayuraggarwal1992** [mmumshad/kubernetes-the-hard-way#30]
Hi Mumshad,

As you already know, these days most of the organization are using Cloud offering for Kubernetes and GKEis a market Leader. In My organization Kubernettes means GKE. I would request can you please make a course on GKE, Exploring it various features and capabilities. There are courses available on coursera but those cover only very small part of it. I hope you would consider this request.

In case you want to contact me you can DM me on Linkedin.

@mmumshad Lecture Request

Thanks,
Mayur Aggarwal

**Comment by fireflycons** [comment]
Hi @Mayuraggarwal1992 

You can raise requests for new courses by going to the following link. If something similar to what you're looking for is already present in the list, simply upvote it else add a new request.
Thanks.

https://kodekloud.com/request-a-course/
