### ISSUE TITLE
TLS Bootstrapping issue

### ISSUE THREAD

**Issue by kack1** [mmumshad/kubernetes-the-hard-way#301]
Hello,

I am currently following this tutorial and ran across and issue. I am trying to TLS bootstrap the worker nodes and ran the `./cert_verify` and it it failed one of the tests 
![Screenshot_2022-11-14_18-21-11](https://user-images.githubusercontent.com/108965613/201796322-839cfa07-d154-48a1-af90-7ea803764c65.png)
I followed the link and it lead me to redoing the certificate authority lab. I glimpsed through both the TLS Bootstrap and the link and could not find any reference to kubelet-client-current.crt anywhere.

I would also like to add I am deriving from this tutorial slightly as I am doing this tutorial on raspberry pis rather than on vm's. So far this is the only time the `./cert_verify` came back as an error. I am uncertain if I did the previous step correctly. The `./cert_verify` came back with no errors when I bootstrapped worker-1. However when I run `kubectl get nodes --kubeconfig admin.kubeconfig` it comes back with no resource found rather than the expected output

Thanks for any help, I know I am deriving from the original tutorial but I thought this would be a fun variation.

**Comment by kack1** [comment]
Turns out my loadbalancer was configured wrong. The HAproxy config file was using the loadbalancer's loopback address and not its static ip address

**Comment by ssaid** [comment]
I'm facing the same issue, and wondering why the loadbalancer could be the problem? :thinking:
