### ISSUE TITLE
Provisioning Pod Network

### ISSUE THREAD

**Issue by mysiar** [mmumshad/kubernetes-the-hard-way#307]
step 13 seems to not working for me somehow

command `kubectl get pods -n kube-system` shows `No resources found in kube-system namespace.` and workers are not ready

**Comment by AudiArduino** [comment]
you can see the issues that I report #303  and #304  you should fix those two otherwise nothing will work

**Comment by Vyom-Yadav** [comment]
Weave won't work for `iptables` version 1.8+ plus this repo uses `IPALLOC_RANGE` as default (10.32.0.0/12) whereas the `POD_CIDR` used throughout the documentation is different. 

Use flannel (if you don't work network policies) or calico or downgrade version of `iptables`.

**Comment by fireflycons** [comment]
Course has been updated for latest kubernetes and fully tested. Please try again if you are still interested.
