### ISSUE TITLE
End-To-End tests expected tests pass / fail ?

### ISSUE THREAD

**Issue by johnlane** [mmumshad/kubernetes-the-hard-way#318]
In part 17, the [end to end tests](https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/17-e2e-tests.md), it says to expect some failures:

> This could take 18 hours or more! There are several thousand tests in the suite. The number of tests run and passed will be displayed at the end. Expect some failures as it tries tests that aren't supported by our cluster, e.g. mounting persistent volumes using NFS.

If one followed the instructions on the provided Vagrant cluster, what would a successful test output be? How many tests should it run, how many falures are expected ?

For example here is the output I got

```
Ran 1140 of 6971 Specs in 77497.301 seconds
FAIL! -- 1009 Passed | 131 Failed | 0 Pending | 5831 Skipped
--- FAIL: TestE2E (77498.52s)
FAIL

Ginkgo ran 1 suite in 21h31m38.605375964s
Test Suite Failed
2023/04/02 11:28:16 process.go:155: Step './hack/ginkgo-e2e.sh ”--ginkgo.focus=[Conformance]”' finished in 21h31m38.851260918s
2023/04/02 11:28:16 main.go:328: Something went wrong: encountered 1 errors: [error during ./hack/ginkgo-e2e.sh ”--ginkgo.focus=[Conformance]”: exit status 1]

```
Is that good or bad?
It would be useful if the lab notes set the expectation.

**Comment by fireflycons** [comment]
Sadly it is unknown exactly how many tests are expected to pass. None of us are members of the Kubertnetes testing SIG.
Put it this way. If the cluster wasn't built correctly, none of the tests would pass.
