### ISSUE TITLE
Modifications to openssl.cnf file needs to be modified taking TLS into consideration

### ISSUE THREAD

**Issue by strikingraghu** [mmumshad/kubernetes-the-hard-way#319]
Hi Team,

With respect to '04-certificate-authority.md' instructions, we need not perform the below step:
     [ sudo sed -i '0,/RANDFILE/{s/RANDFILE/\#&/}' /etc/ssl/openssl.cnf ]

As per the latest RHEL 8.4 version, we see TLS being used by default and this file is located in below path and managed by PKI concept:
     [ /etc/pki/tls/openssl.cnf ]

Hence, can you please review the need of this step and update this block?

**Comment by fireflycons** [comment]
Hi,
We are currently refreshing this guide to latest kube version. This will be addressed as par tof the refresh.
Thanks
