### ISSUE TITLE
docs/17-e2e-tests.md breaks because of go version 1.18

### ISSUE THREAD

**Issue by MrVenelin** [mmumshad/kubernetes-the-hard-way#322]
Hi,

docs/17-e2e-tests.md aborts with "/pkg/cached/cache.go:242:16: undefined: atomic.Pointer" when go version is 1.18. I installed go version 1.19 and “go build” was successful.

I did the following:
vagrant ssh master-1
sudo rm -rf /usr/local/go

wget https://dl.google.com/go/go1.19.linux-amd64.tar.gz

sudo tar -C /usr/local -xzf go1.19.linux-amd64.tar.gz

It would be great to change this to be able to do the end-to-end tests.

Best Regards
Venelin

**Comment by fireflycons** [comment]
Hi,
We are currently refreshing this repo for latest Kubernetes version. e2e tests will be fixed as part of this.
Should be done in the next week or so

Thanks
