### ISSUE TITLE
Instructions to setup k8s on Mac M1/M2 using UTM instead of VirtualBox

### ISSUE THREAD

**Issue by kamal2222ahmed** [mmumshad/kubernetes-the-hard-way#324]
Looking at the README:
```IMPORTANT This currently does not work on Apple M1/M2. Oracle are yet to release a compatible version for these systems.```

Perhaps we can try to get this work on M1/M2 with UTM? and issue a set of instructions, or just have a Note that In order for the solution to work on Mac M1/M2, you can use UTM instead of VirtualBox ( VirtualBox is not available on M1/M2 )

**Comment by fireflycons** [comment]
You can also use Multipass on Apple Silicon.
There will be an update here for that in future.
