### ISSUE TITLE
Lacture request for certified-kubernetes-administrator-with-practice-tests

### ISSUE THREAD

**Issue by KishanP-protean** [mmumshad/kubernetes-the-hard-way#329]
### Your Workstation

Hi Sir,Maam

i have purchase the [Certified Kubernetes Administrator (CKA) with Practice Tests] on udemy
(https://www.udemy.com/course/certified-kubernetes-administrator-with-practice-tests/)

in which i have found from official doc current Kubernetes version is V1.28 
(Kubernetes v1.28)
(https://v1-28.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/)  

![image](https://github.com/kodekloudhub/certified-kubernetes-administrator-course/assets/57756712/e85d5e54-f4ad-4719-a4cb-d7d78328bd00)

but on udemy course is updated till to V1.27. 
![image](https://github.com/kodekloudhub/certified-kubernetes-administrator-course/assets/57756712/2812f919-e1b0-4fa2-895f-73a20d04e527)

please check and update the course if there is any update in this course.

Thanks Regards 
kkishanppanchal@gmail.com 

### What happened?

A bug happened!

**Comment by fireflycons** [comment]
There are no significant changes that affect the CKA course between 1.27 and 1.28. You need not worry.

Please use our forum to raise questions such as this: https://community.kodekloud.com/
Thanks

**Comment by xyzkpz** [comment]
Thank you @fireflycons Sir...!!!
