### ISSUE TITLE
Lecture Request: Seperate coure or module for Installing Kubernetes cluster

### ISSUE THREAD

**Issue by pugazhendhiramakrishnan08121985** [mmumshad/kubernetes-the-hard-way#330]
### Your Workstation

Windows 10 Laptop, 16 GB RAM, 8 core i7 CPU

### What happened?

Would like to see a course on Kubernetes installation on various scenarios from bare metal, cloud, virtualization, single master, multi master. Managing multiple cluster etc...

**Comment by fireflycons** [comment]
Hello
Please see the following:
* https://github.com/kodekloudhub/certified-kubernetes-administrator-course/tree/master/kubeadm-clusters
* https://github.com/kodekloudhub/certified-kubernetes-administrator-course/tree/master/managed-clusters/eks

For general questions not directly related to this repo, please use our forum here https://community.kodekloud.com/
