### ISSUE TITLE
Lecture Request: Unable to find anything related to stateful set in CKA

### ISSUE THREAD

**Issue by pugazhendhiramakrishnan08121985** [mmumshad/kubernetes-the-hard-way#331]
### Your Workstation

Windows 10 Laptop, 16 GB RAM, 8 core i7 CPU

### What happened?

I'm learning CKA, CKAD, as of now I completed most of the topics in CKA but can't find anything related to Stateful set. Can you please confirm if that is covered in any of the course and I missed it or it is not part of the curriculam.

**Comment by fireflycons** [comment]
Please use our forums to ask such questions.
https://kodekloud.com/community/
