### ISSUE TITLE
[Bug]: weaveworks plugin not available

### ISSUE THREAD

**Issue by samlap1984** [mmumshad/kubernetes-the-hard-way#332]
### Your Workstation

AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz

24 GB

Windows 11

### What happened?

can't install the weavework plugin because weavework is closed

so which plugin can I take to continue this lab?

I try to find a plugin in github but maybe it's me i'm too noob to find it...

### Relevant output

```shell
kubectl apply -f "https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s-1.11.yaml"



Error from server: error when retrieving current configuration of:
Resource: "/v1, Resource=serviceaccounts", GroupVersionKind: "/v1, Kind=ServiceAccount"
Name: "weave-net", Namespace: "kube-system"
from server for: "https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s-1.11.yaml": etcdserver: request timed out


https://www.linkedin.com/posts/richardsonalexis_hi-everyone-i-am-very-sad-to-announce-activity-7160295096825860096-ZS67/

https://www.weave.works/docs/net/latest/kubernetes/kube-addon/
```

**Comment by fireflycons** [comment]
Hi @samlap1984 

I'm aware of the announcement from WeaveWorks CEO, however they have not taken down their github site. 
If you follow the link https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s-1.11.yaml in your browser, it should download the file, which means you probably have an issue reaching the internet in the VM that tried the download.
