### ISSUE TITLE
Topic 

### ISSUE THREAD

**Issue by Lokesh-anji** [mmumshad/kubernetes-the-hard-way#335]
### Your Workstation

Windows 10 Laptop, 16 GB RAM, 8 core i7 CPU

### What happened?

Include topic 

### Relevant output

```shell
Hi Sir,

Please include external name service.
```

**Comment by fireflycons** [comment]
Not sure what you mean.
This repo is not about doing things on a working cluster. It merely serves to illustrate what is involved to *build* a highly available cluster from scratch, not using any tools that assist with e.g. creating PKI as kubeadm does for you.
