### ISSUE TITLE
[Bug]: ETCD restore issue

### ISSUE THREAD

**Issue by Velan987** [mmumshad/kubernetes-the-hard-way#336]
### Your Workstation

Windows 10 Laptop, 16 GB RAM, 8 core i7 CPU

### What happened?

I am following below file to restore etcd backup.
https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/practice-questions-answers/cluster-maintenance/backup-etcd/etcd-backup-and-restore.md
I have 3 control plane with **stacked etcd** cluster, when i try to restore etcd backup, etcd pod is not coming in "running" state. I am restoring the backup to separate data-directory and modifying the etcd.yaml manifest file.
I also tried deleting /var/lib/etcd and restored the backup in /var/lib/etcd in this case etcd pod is healthy but it is acting as separate member, not joining in to existing etcd cluster.

**Comment by fireflycons** [comment]
Hello @Velan987 

This is not the place to ask such questions. Please ask on the [Community Forum](https://kodekloud.com/community/).
