### ISSUE TITLE
Lecture request

### ISSUE THREAD

**Issue by harishmurkal** [mmumshad/kubernetes-the-hard-way#34]
Hi,

Can you please cover following topics, please? (I'm half way through the courses and hence not sure if you have already covered in remaining topics. Anyways, if it's already present please point out)

1. Node Allocatables
2. POD Eviction Policies, OOM behavior

Thanks and Regards,
Harish M

**Comment by fireflycons** [comment]
Hi @harishmurkal 

If by 1. you mean scheduling of pods to desired nodes (affinity/anti-affinity/tolerations etc), it is covered by CKA.

You can raise requests for new courses by going to the following link. If something similar to what you're looking for is already present in the list, simply upvote it else add a new request.
Thanks.

https://kodekloud.com/request-a-course/
