### ISSUE TITLE
[Bug]: step 5 verifying kubeconfig files fails for admin.kubeconfig.

### ISSUE THREAD

**Issue by sandeepV2** [mmumshad/kubernetes-the-hard-way#350]
### Your Workstation

Apple Silicon Mac (M1/M2/M3)

### System Memory

16GB or more

### What happened?

Generated admin kubeconfig as per this instructions:
https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/05-kubernetes-configuration-files.md#the-admin-kubernetes-configuration-file

copied to controlplane01 and contolplane02 nodes/VMs.

I see that admin.kubeconfig is available in controlplane01. 

> ubuntu@controlplane01:~$ ls -l admin.kubeconfig 
> -rw------- 1 ubuntu ubuntu 1704 Oct  7 08:17 admin.kubeconfig 

Verifying the same with cert_verify as per instructions [here](https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/05-kubernetes-configuration-files.md#optional---check-kubeconfigs), **Fails with below error**

Though it is Optional !, will it have failures going forward in any way ?

> ubuntu@controlplane01:~$ bash cert_verify.sh 
> This script will validate the certificates in master as well as node01 nodes. Before proceeding, make sure you ssh into the respective node [ Master or Worker-1 ] for certificate validation
> 
>   1. Verify certificates on Master Nodes after step 4
>   2. Verify kubeconfigs on Master Nodes after step 5
>   3. Verify kubeconfigs and PKI on Master Nodes after step 8
>   4. Verify kubeconfigs and PKI on node01 Node after step 10
>   5. Verify kubeconfigs and PKI on node02 Node after step 11
> 
> Please select one of the above options: 2 
> admin kubeconfig file found, verifying the authenticity
> Could not read certificate from <stdin>
> Unable to load certificate
> Could not read certificate from <stdin>
> Unable to load certificate
> Could not read certificate from <stdin>
> Unable to load certificate
> Could not read private key from <stdin>
> cert_verify.sh: line 186: [: ==: unary operator expected
> Exiting...Found mismtach in the admin kubeconfig certificate and keys, More details: https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/05-kubernetes-configuration-files.md#the-admin-kubernetes-configuration-file 

### Relevant output

```shell
Output of admin.kubeconfig file.
ubuntu@controlplane01:~$ cat admin.kubeconfig 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQWNrQ0ZHbDZCd1lOclJXWGZob0IxTWhwNEVoQURqTTJNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DMHgKRmpBVUJnTlZCQU1NRFV0VlFrVlNUa1ZVUlZNdFEwRXhFekFSQmdOVkJBb01Da3QxWW1WeWJtVjBaWE13SGhjTgpNalF4TURBMk1EVTFOak0xV2hjTk1qY3dOekF6TURVMU5qTTFXakF0TVJZd0ZBWURWUVFEREExTFZVSkZVazVGClZFVlRMVU5CTVJNd0VRWURWUVFLREFwTGRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0MKQVE4QU1JSUJDZ0tDQVFFQTZyaHp3NUR6amhqNW9JOGhEVGZqRWdpZFIzM2tlWVZRODkwUFl5czNQUC9JSkZoNwppY1p6SlgyRytwSUlFZTVOTEI3Y0ZySEhEc3VLczNXVGhHREExSHBnRENJT0ZmSVdWS1VVMUdJTnZyS0hXSVpvClQ2c2psaEZlbzlqdEM1cjd6YWQ2K3pyaEw1YWJtL3h3M0Z5Y1dkaXc5aVBKaFE5YnVkUDZ1UFIwViszTEtIK0wKbllnOGxYV01zZVhkeWorcGU2UlQyd0JLQkFwWDNFVldZSnBwU21xdjhwYUgyY0I0Tm5NMmdHdlIxZFl4SWZqTAo5Rlh5MU9LdTFGMkpBZmoxbmI5eWFXS1A4aDFFWnhBa0Y2TEdZZ09qU3FIZ0F3V2hYbjQwNk0zaS9WbGlWbGp6CmVCWFhCZEhSa1h4U0l2QTBBKzIvM3J1R0lxUVBYYVRJSVBmNktRSURBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUEKQTRJQkFRQVU2Umw3TkIzNXJWY1lOMDlVWnZIa21FdlJncCtTTk9NV0xVWitKZHFNVC9IRzlndDQ1RlB0UzNFdgpjZHFZeTRTdC94ZXZHWFhQZDRxWFZSVTYxTTRyN0RreGFpTmFjZEFvdFFMTFNFUEtzQjBLV3V3ajg0cGRxRC9KCmlPellxcDdWN3h1RWJxd2VBaGMvdTVZeXgrTVNCd09Camp6akhPRmJQMEswN012Q1ZFcXkwNTU0ZldtUlEvNlcKL09oNTBmblQvd1oyclFGQzNKQWJtS2dVN3JBaHJmZDJYWGVwdnRQdFFCYVVzdEw3cUR5bk5DaElpaTRmL2hlcQp3dG1DYWVlbXFBL2lXeUlnUjhzdnRlWTVEK2lGZG4rdURMYi9sRHZ1VVRwK2IwL2xxVXFMdGZjbWR0WGZyOUI2Cms0TTNuRHpMbThiU1l5N0xtZ1NMNXNDR1F3ZWYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://127.0.0.1:6443
  name: kubernetes-the-hard-way
contexts:
- context:
    cluster: kubernetes-the-hard-way
    user: admin
  name: default
current-context: default
kind: Config
preferences: {}
users: null
```

**Comment by fireflycons** [comment]
Let's see the content of the admin.kubeconfig certificate

1. Verify the kubeconfig was actually created
    ```
    ls -l admin.kubeconfig
    ```
2. Extract certificate data
    ```
    cat admin.kubeconfig |  grep "client-certificate-data:" | awk '{print $2}' | base64 --decode | sudo openssl x509 -text
    ````
3. In the output from the above, look for `Subject` and `Issuer` lines. They should look like this

   ```
   Subject:CN=admin,O=system:masters
   ```
   
   ```
   Issuer:CN=KUBERNETES-CA,O=Kubernetes
   ```
   
   If the above is all good you should be OK to continue. If not, you have made a mistake somewhere in the steps before this.

**Comment by fireflycons** [comment]
Hold on.
Is what you put in "Relevant output" your *entire* `admin.kubeconfig`?

You are missing the `users` section containing the client certificate which is what is being checked here.

It suggests that you missed out this command

```
  kubectl config set-credentials admin \
    --client-certificate=admin.crt \
    --client-key=admin.key \
    --embed-certs=true \
    --kubeconfig=admin.kubeconfig
```

**Comment by sandeepV2** [comment]
Wow @fireflycons .  

Thats was to the point, yes there was no `client-certificate-data`. Regenerated the all kubeconfig files on controlplane01 and copied to controlplane02. 

> ubuntu@controlplane02:~$ bash cert_verify.sh 
> This script will validate the certificates in master as well as node01 nodes. Before proceeding, make sure you ssh into the respective node [ Master or Worker-1 ] for certificate validation
> 
>   1. Verify certificates on Master Nodes after step 4
>   2. Verify kubeconfigs on Master Nodes after step 5
>   3. Verify kubeconfigs and PKI on Master Nodes after step 8
>   4. Verify kubeconfigs and PKI on node01 Node after step 10
>   5. Verify kubeconfigs and PKI on node02 Node after step 11
> 
> Please select one of the above options: 2
> admin kubeconfig file found, verifying the authenticity
> admin kubeconfig cert and key are correct
> /home/ubuntu/kube-controller-manager.kubeconfig found
> /home/ubuntu/kube-scheduler.kubeconfig found

**Comment by fireflycons** [comment]
No worries @sandeepV2 

I'm the maintainer for this repo :wink:

There will be a new version of this soon which will use VMware Fusion and Vagrant - so that it uses the same vagrant file as Windows and older Intel Macs.
All the other courses where we build home labs on virtual machines will be done this way.

**Comment by fireflycons** [comment]
And bear in mind with this lab, that if you miss one single command no matter how small it seems, things will break, as you have just found out!

**Comment by sandeepV2** [comment]
One thing to note here is that, instructions for creating a admin kubeconfig are all together as copiable chunk. 

https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/05-kubernetes-configuration-files.md#the-admin-kubernetes-configuration-file 

The commands executed in batches, one of them like adding client certificate would have failed. Users must be alert on exit status of the given commands too :-) 
I am using Apple silicon chip,( multipass for getting the vms.).

**Comment by sandeepV2** [comment]
@fireflycons can we move this to discussion rather than a bug and close the thread. Thanks again.

**Comment by fireflycons** [comment]
closed
