### ISSUE TITLE
Lecture Request

### ISSUE THREAD

**Issue by bibin-skaria** [mmumshad/kubernetes-the-hard-way#37]
I want more in depth lecture on following topics.

-Auto scaling a cluster

-Horizontal POD autoscalers

**Comment by fireflycons** [comment]
Hi @bibin-skaria 

You can raise requests for new courses by going to the following link. If something similar to what you're looking for is already present in the list, simply upvote it else add a new request.
Thanks.

https://kodekloud.com/request-a-course/
