### ISSUE TITLE
@mmumshad Scheduling presentation PDF is missing labels &amp; Selectors and Resource Limit section

### ISSUE THREAD

**Issue by mmumshad** [mmumshad/kubernetes-the-hard-way#46]
@mmumshad Scheduling presentation PDF is missing labels &amp; Selectors and Resource Limit section

https://kodekloud.slack.com/archives/CHMV3P9NV/p1572722266026200

**Comment by Tej-Singh-Rana** [comment]
I assigned it to the concerned team.
