### ISSUE TITLE
Add a prompt with a server name where all steps are to be run

### ISSUE THREAD

**Issue by przemolb** [mmumshad/kubernetes-the-hard-way#63]
Some of these steps are nut fully clear which server they should run on (master(s) ? worker(s) ? which worker ?).
Please add a prompt to each snippet showing where all these commands should be run on.

**Comment by kumareshr** [comment]
it's feel like documents are not well structure and in course video just copy/paste this doc without proper explanation, Please add little more info on video

**Comment by fireflycons** [comment]
Hi @przemolb 

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. 
I realise this is a very old issue, however I was tasked with closing off all old issues following the upgrade.
Please try it now and feel free to raise further issues.

Thanks.
