### ISSUE TITLE
Boot strap issue kube-controller & Kube-scheduler unhealthy

### ISSUE THREAD

**Issue by kantharajmurugan** [mmumshad/kubernetes-the-hard-way#66]
Boot strap issue kube-controller & Kube-scheduler getting error.

root@master-1:~/test# kubectl get componentstatuses --kubeconfig admin.kubeconfig
NAME                 STATUS      MESSAGE                                                                                     ERROR
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused
etcd-0               Healthy     {"health":"true"}
etcd-1               Healthy     {"health":"true"}

Based on the https://github.com/kubernetes/kops/issues/463 link. I have added the entry in listed below file. 

--master=127.0.0.1:8080 \ 

/etc/systemd/system/kube-controller-manager.service /etc/systemd/system/kube-scheduler.service

The reported issue got resolved. 
root@master-1:/var/lib/kubernetes# kubectl get componentstatus
NAME                 STATUS    MESSAGE             ERROR
scheduler            Healthy   ok
controller-manager   Healthy   ok
etcd-0               Healthy   {"health":"true"}
etcd-1               Healthy   {"health":"true"}

**Comment by kesaraw** [comment]
same thing happened to me.
Please append these to config files which would save our time definitely

**Comment by kilyes** [comment]
thanks @kantharajmurugan

**Comment by RobertoBorges** [comment]
thank @kantharajmurugan that solved my issue as well

**Comment by fireflycons** [comment]
Hi @kantharajmurugan @kesaraw @kilyes @RobertoBorges 

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. 
I realise this is a very old issue, however I was tasked with closing off all old issues following the upgrade.
Please try it now and feel free to raise further issues.

Thanks.
