### ISSUE TITLE
Replace "The Hard Way" with "HA Clusters-Kubeadm way" in CKA course

### ISSUE THREAD

**Issue by dehad** [mmumshad/kubernetes-the-hard-way#73]
Hi @mmumshad 
To me is quite useless to build cluster form scratch hard way in the CKA exam. 
Kubeadm tool support building HA clusters and it would be worth to create lecture and exercises building HA Cluster in Kubeadm way, since this is default tool required for CKA exam. In the real life if you gonna to build cluster most probably you wound't go hard way.

**Comment by cweibel** [comment]
I don't think the intention of this exercise/repo was meant directly for questions on the CKA exam, rather to show you how all the certs and components are glued together for a better understanding of the moving pieces.

Mumshad has other training course materials including one that brings you through how to `Install Kubernetes with kubeadm` at [https://www.udemy.com/course/certified-kubernetes-administrator-with-practice-tests/learn/lecture/17174028#overview](https://www.udemy.com/course/certified-kubernetes-administrator-with-practice-tests/learn/lecture/17174028#overview) which leverages vms provisioned on KodeKloud.  

If you don't have access to that training material you could use the Vagrantfile in this repo to provision the ubuntu vms and then run through https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

Note: I'm not a maintainer or have any vested interest in this repo, just happened to be looking for a Vagrantfile to setup a kubernetes cluster and stumbled across this.  Good luck!

**Comment by mmumshad** [comment]
@dehad  Thanks for your suggestions. We do have many lectures and demos on deploying Kubernetes using kubeadm tool along with labs and practice tests in our course. This repo was meant to understand how things are wired together in a Kubernetes cluster and it helps while troubleshooting issues.

@cweibel  Thanks for your response.
