### ISSUE TITLE
Explanation Mistake

### ISSUE THREAD

**Issue by RonaldCrb** [mmumshad/kubernetes-the-hard-way#76]
On video 10, minute 7:12 of Kubernetes Certified Aplication Developer course, you mention Multi-pod containers, instead of Multi-containers Pod. as the explanation is near perfect, it might as well be worth it to fix that :)

**Comment by fireflycons** [comment]
Hi @RonaldCrb 

I realise this is a very old issue, however I was tasked with closing off all old issues.
For issues such as this, please post on https://community.kodekloud.com/

Thanks.
