### ISSUE TITLE
Unable to access Deployments and Namespace practice tests

### ISSUE THREAD

**Issue by sbalu300** [mmumshad/kubernetes-the-hard-way#77]
Hi ,

I am unable to access deployments and Name space practice tests,pls do the needful

Thanks and Regards
Balaji

**Comment by sbalu300** [comment]
<img width="657" alt="errorudemy" src="https://user-images.githubusercontent.com/59280157/71780225-d1143480-2fe5-11ea-918e-fa02e6765d35.PNG">

pls find the error

**Comment by fireflycons** [comment]
Hi @sbalu300 

I realise this is a very old issue and is probably long since solved, however I was tasked with closing off all old issues following the upgrade.
For issues such as this, reach out to support@kodekloud.com

Thanks
