### ISSUE TITLE
Worker Nodes (No Resource Found)

### ISSUE THREAD

**Issue by justrehan86** [mmumshad/kubernetes-the-hard-way#78]
Hello,

Thank you for setting up the great trainings, I have got stuck in this for last 2 days, tried to troubleshoot but no success,

After Bootstrapping worker and master, When I do KUBECTL GET NODES , I get an error no resource found , When I do following for component get following eroor

**kubectl get componentstatuses
The connection to the server 192.168.5.30:6443 was refused - did you specify the right host or port?**
Where can I look for possible issue

**Comment by ssmiller25** [comment]
I would look closely at your haproxy configuration.  The configuration on that VM was at https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md#the-kubernetes-frontend-load-balancer  Did the debugging steps work (the `curl  https://192.168.5.30:6443/version -k` from the worker nodes)?

**Comment by fireflycons** [comment]
Hi @justrehan86 @ssmiller25 

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. 
I realise this is a very old issue, however I was tasked with closing off all old issues following the upgrade.
Please try it now and feel free to raise further issues.

Thanks.
