### ISSUE TITLE
Vagrant files to install docker on the on the nodes

### ISSUE THREAD

**Issue by mokua** [mmumshad/kubernetes-the-hard-way#83]
after running vagrant up , docker is not installed on the nodes.
This has to be installed separately.

**Comment by gopukrishnantec** [comment]
I was able to reproduce the issue. I think the curl command is not able to download the packages to /tmp and followed the failure.
vagrant@worker-2:~$ cd /tmp/
vagrant@worker-2:/tmp$ curl -fsSL https://get.docker.com -o get-docker.sh
curl: (23) Failed writing body (0 != 13328)
appending a sudo would do
proposed : 
cat install-docker-2.sh
cd /tmp
sudo curl -fsSL https://get.docker.com -o get-docker.sh
sh /tmp/get-docker.sh
