### ISSUE TITLE
09-bootstrapping-kubernetes-workers.md: prerequisites 

### ISSUE THREAD

**Issue by mokua** [mmumshad/kubernetes-the-hard-way#85]
The section *The commands in this lab must be run on first worker instance: worker-1. Login to first worker instance using SSH Terminal.*

worker-1 ==> should be server-1

**Comment by fireflycons** [comment]
Hi @mokua 

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. 
I realise this is a very old issue, however I was tasked with closing off all old issues following the upgrade.
Please try it now and feel free to raise further issues.

Thanks.
