### ISSUE TITLE
"generator:RAND_load_file:Cannot open file" error during CSR creation

### ISSUE THREAD

**Issue by tcdowney** [mmumshad/kubernetes-the-hard-way#86]
I ran into this `generator:RAND_load_file:Cannot open file` error while working on [step 4](https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md) using openssl version `1.1.1`.

```bash
vagrant@master-1:~$ openssl req -new -key ca.key -subj "/CN=KUBERNETES-CA" -out ca.csr
Can't load /home/vagrant/.rnd into RNG
140386097500608:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/home/vagrant/.rnd
```

I found this issue https://github.com/openssl/openssl/issues/7754 and it mentioned removing the `RANDFILE=` assignment from `openssl.cnf`.

So I `sudo vim /usr/lib/ssl/openssl.cnf` and removed it which seems to have resolved things. Just noting this here in case other folks are running into this!

**Comment by fireflycons** [comment]
Hi @tcdowney 

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. 
I realise this is a very old issue, however I was tasked with closing off all old issues following the upgrade.
Please try it now and feel free to raise further issues.

Thanks.
