### ISSUE TITLE
Error while running vagrant up

### ISSUE THREAD

**Issue by faizanbashir** [mmumshad/kubernetes-the-hard-way#91]
While running the `vagrant up` command I get the following error:

```
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and that enough disk space
is available and then try again.
The output from attempting to unpackage (if any):

x box.ovf
x Vagrantfile
x metadata.json
x ubuntu-bionic-18.04-cloudimg.mf
x ubuntu-bionic-18.04-cloudimg.vmdk: Truncated tar archive
bsdtar: Error exit delayed from previous errors.
```

I tried running this on MacOS `Mojave 10.14.6` and on Ubuntu 18.04 EC2 instance, I am getting this error on Mac. Please help I am not able to proceed further due to this.

**Comment by Partridje** [comment]
Yes!
I would like to ask the same thing)

**Comment by faizanbashir** [comment]
Seems like there is some issue with the `ubuntu/bionic64` box. For now, I have updated the box to `ubuntu/xenial64`.

The update can be done in the Vagrantfile like so:
```
config.vm.box = "ubuntu/xenial64"
```

**Comment by Partridje** [comment]
@faizanbashir Thanks a lot!
It works for mw as well :)

**Comment by faizanbashir** [comment]
You are welcome.
