### ISSUE TITLE
vagrant up fails to complete the dockerce script

### ISSUE THREAD

**Issue by mhshamim** [mmumshad/kubernetes-the-hard-way#97]
PS D:\Kubernetes\kubernetes-the-hard-way\vagrant> vagrant up worker-1                                                   Bringing machine 'worker-1' up with 'virtualbox' provider...
==> worker-1: Importing base box 'ubuntu/bionic64'...
==> worker-1: Matching MAC address for NAT networking...
==> worker-1: Setting the name of the VM: kubernetes-ha-worker-1
==> worker-1: Clearing any previously set network interfaces...
==> worker-1: Preparing network interfaces based on configuration...
    worker-1: Adapter 1: nat
    worker-1: Adapter 2: hostonly
==> worker-1: Forwarding ports...
    worker-1: 22 (guest) => 2721 (host) (adapter 1)
    worker-1: 22 (guest) => 2222 (host) (adapter 1)
==> worker-1: Running 'pre-boot' VM customizations...
==> worker-1: Booting VM...
==> worker-1: Waiting for machine to boot. This may take a few minutes...
    worker-1: SSH address: 127.0.0.1:2222
    worker-1: SSH username: vagrant
    worker-1: SSH auth method: private key
    worker-1: Warning: Connection aborted. Retrying...
    worker-1:
    worker-1: Vagrant insecure key detected. Vagrant will automatically replace
    worker-1: this with a newly generated keypair for better security.
    worker-1:
    worker-1: Inserting generated public key within guest...
    worker-1: Removing insecure key from the guest if it's present...
    worker-1: Key inserted! Disconnecting and reconnecting using new SSH key...
==> worker-1: Machine booted and ready!
==> worker-1: Checking for guest additions in VM...
    worker-1: The guest additions on this VM do not match the installed version of
    worker-1: VirtualBox! In most cases this is fine, but in rare cases it can
    worker-1: prevent things such as shared folders from working properly. If you see
    worker-1: shared folder errors, please make sure the guest additions within the
    worker-1: virtual machine match the version of VirtualBox you have installed on
    worker-1: your host and reload your VM.
    worker-1:
    worker-1: Guest Additions Version: 5.2.34
    worker-1: VirtualBox Version: 6.1
==> worker-1: Setting hostname...
==> worker-1: Configuring and enabling network interfaces...
==> worker-1: Mounting shared folders...
    worker-1: /vagrant => D:/Kubernetes/kubernetes-the-hard-way/vagrant
==> worker-1: Running provisioner: setup-hosts (shell)...
    worker-1: Running: C:/Users/mhs/AppData/Local/Temp/vagrant-shell20200309-13116-1wghjso.sh
==> worker-1: Running provisioner: setup-dns (shell)...
    worker-1: Running: C:/Users/mhs/AppData/Local/Temp/vagrant-shell20200309-13116-1hqoaqf.sh
==> worker-1: Running provisioner: install-docker (shell)...
    worker-1: Running: C:/Users/mhs/AppData/Local/Temp/vagrant-shell20200309-13116-kgm0i6.sh
    worker-1: # Executing docker install script, commit: 442e66405c304fa92af8aadaa1d9b31bf4b0ad94
    worker-1: +
    worker-1: sh
    worker-1:  -c
    worker-1:  apt-get update -qq >/dev/null
    worker-1: + sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
    worker-1: + sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
    worker-1: Warning: apt-key output should not be parsed (stdout is not a terminal)
    worker-1: + sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" > /etc/apt/sources.list.d/docker.list
    worker-1: + sh -c apt-get update -qq >/dev/null
    worker-1: +
    worker-1: [
    worker-1:  -n
    worker-1:   ]
    worker-1: + sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
    worker-1: E
    worker-1: : Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/containerd.io_1.2.13-1_amd64.deb  Hash Sum mismatch
    worker-1:    Hashes of expected file:
    worker-1:     - SHA512:45640591cd629a357cdf4ab3b5225dd8c4ce3f7100ab35b776502224014c76db164f849f52bf044919b01a4acbb075a11aacc514d386af398c6f93ba7ef35e2e
    worker-1:     - SHA256:e0f9d311a77ce0729a25f41925f6b3174616f704fd21bbc7c4d91a1012f360a8
    worker-1:     - SHA1:4c7a98e8145fb258c24044c78f6f1f8abc1f6893 [weak]
    worker-1:     - MD5Sum:7eaf2d7d924a20d6fbf1ce8cd155b67e [weak]
    worker-1:     - Filesize:20144902 [weak]
    worker-1:    Hashes of received file:
    worker-1:     - SHA512:12b52543692c4fa534a2c496d47a1344fd84f7e2458596e20b753954d8690bfa5bc8908b4959ad69408aac964d25cfe59e74115852e1bbfee845bc6e179666e9
    worker-1:     - SHA256:4034d0d3b76054826f20da9ae890886c15437f10950ef9c517dccce506eb953c
    worker-1:     - SHA1:9970f5824f3b2305aaed246f936fa358ce692401 [weak]
    worker-1:     - MD5Sum:3d69bc59d3a7ce5b3a237742b140145b [weak]
    worker-1:     - Filesize:20144902 [weak]
    worker-1:    Last modification reported: Tue, 03 Mar 2020 04:23:27 +0000
    worker-1: E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce-cli_19.03.7~3-0~ubuntu-bionic_amd64.deb  Hash Sum mismatch
    worker-1:    Hashes of expected file:
    worker-1:     - SHA512:901541070d59c6d89fd76a19415ced4cdf8c596515bae350a9e100001107e31a6eb5937402fcfc80ef049a5bc7a6c8065ff813f7d3067229f98ee8a6e7b7623c
    worker-1:     - SHA256:89fd8a89cbebaecaf4169272b43d99ad3aa2f46b1224560a840c0d3726f2c913
    worker-1:     - SHA1:98ece988104a21eaaf548551729b25f3bd8fdbce [weak]
    worker-1:     - MD5Sum:d7c03603b986a503ccc327361a606a82 [weak]
    worker-1:     - Filesize:42545318 [weak]
    worker-1:    Hashes of received file:
    worker-1:     - SHA512:2f1fda5410752496145e72f1f3d9f564004f94a129d52d8ade9d2a63976289918016ecc26dacb117fc8ca7c6f8b0195c653374b9bbebde34b9770cd9bfacd4bd
    worker-1:     - SHA256:6bdcb07b73e0c75652b04be2381853605fdde807389646adeb97281e8fcd7a3d
    worker-1:     - SHA1:445eca66ed2d0fb611e92f87b23b40f4e6328e75 [weak]
    worker-1:     - MD5Sum:e2411c63fe581022988eada859d0cb5b [weak]
    worker-1:     - Filesize:42545318 [weak]
    worker-1:    Last modification reported: Wed, 04 Mar 2020 05:37:34 +0000
    worker-1: E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce_19.03.7~3-0~ubuntu-bionic_amd64.deb  Hash Sum mismatch
    worker-1:    Hashes of expected file:
    worker-1:     - SHA512:7a65ebccfd308715e7d03cb7ae4aef7843ad8335c3571b2496be07b56340a79abd3b08ec751801a39ccd1adeb8ca12694b29a5adc85b6a3fcc51fca0a84852cc
    worker-1:     - SHA256:b8383aa4bb685e910cfa9305f40c8a3e375843e594b4ec5eb01d0b5c83e5087f
    worker-1:     - SHA1:5cf229ed1b5f8314cbce13f3e560c8b4510e13ff [weak]
    worker-1:     - MD5Sum:97be317fec13adee6b3daf716c6add7e [weak]
    worker-1:     - Filesize:22871562 [weak]
    worker-1:    Hashes of received file:
    worker-1:     - SHA512:23abf050ba870861159709443dd84c11d8975005d2a5a200cf47c15f0f3040e6b6e7d7bf0b359b68348c271bbcbdd5ccb41913cd601ae81b7821fd2c4d1cf2f2
    worker-1:     - SHA256:7502622f4f0de02429e3899c7b9cde4ffa2caf659fe796a6b5669dd2a45e7259
    worker-1:     - SHA1:6e15b61ce8b33d38ba2e3e8f87f0c509a366c8b0 [weak]
    worker-1:     - MD5Sum:0a57c6dd0d7619c1787a3146b4b951ed [weak]
    worker-1:     - Filesize:22871562 [weak]
    worker-1:    Last modification reported: Wed, 04 Mar 2020 05:37:35 +0000
    worker-1: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by mhshamim** [comment]
I tried several times with fresh machines, but still the issue remains same.... it fails to fetch and gives error in hash sum mismatch.

**Comment by susilj** [comment]
worker-1: + sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
    worker-1: E
    worker-1: :
    worker-1: Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/containerd.io_1.2.13-1_amd64.deb  Hash Sum mismatch
    worker-1:    Hashes of expected file:
    worker-1:     - SHA512:45640591cd629a357cdf4ab3b5225dd8c4ce3f7100ab35b776502224014c76db164f849f52bf044919b01a4acbb075a11aacc514d386af398c6f93ba7ef35e2e
    worker-1:     - SHA256:e0f9d311a77ce0729a25f41925f6b3174616f704fd21bbc7c4d91a1012f360a8
    worker-1:     - SHA1:4c7a98e8145fb258c24044c78f6f1f8abc1f6893 [weak]
    worker-1:     - MD5Sum:7eaf2d7d924a20d6fbf1ce8cd155b67e [weak]
    worker-1:     - Filesize:20144902 [weak]
    worker-1:    Hashes of received file:
    worker-1:     - SHA512:6cdd7d48eff676a1f7cd59b80c90623606b1d84956ee3257f8114f14e7a55cfbadd0e52ec06e53b593f7aca7512eb3061081fb663dc1a0514fa7bc39d295544c
    worker-1:     - SHA256:0b9deefd7c6865bc017ec531f71c045e3ac5c04faacf059f2af73b8a28ceafaf
    worker-1:     - SHA1:63249617dcc893f2cbe71d6c320f5b2a43bd6b5e [weak]
    worker-1:     - MD5Sum:1923f3a3a64e7b188dea2aa551aeb227 [weak]
    worker-1:     - Filesize:20144902 [weak]
    worker-1:    Last modification reported: Tue, 03 Mar 2020 04:23:27 +0000
    worker-1: E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce-cli_19.03.8~3-0~ubuntu-bionic_amd64.deb  Hash Sum mismatch
    worker-1:    Hashes of expected file:
    worker-1:     - SHA512:f2b86f90af0233ffac36743f8a567ab3df2ab8d03196707ca9eae606b796499f2c99b34380feab11b84ec895e5c470c656e0f4fccf149eba25799910fa593ca1
    worker-1:     - SHA256:b3942ad3191de83eb3540f5096dc27783fff8de21227ad5f94fec194fcc3c2e7
    worker-1:     - SHA1:1ae24a9b73cbc7ca4a048ac204a4470df4d2bc80 [weak]
    worker-1:     - MD5Sum:59f94df4a18df9ad4d9e34718e210742 [weak]
    worker-1:     - Filesize:42556330 [weak]
    worker-1:    Hashes of received file:
    worker-1:     - SHA512:ac591d5ea372a301f67529c810f65732aa0e460b2be0a73ebee1b3d2f91a33909c502c73ea3f8624921fa4d6b4aa011c3180bad94c74c74c4fe07a18b5cdc7ef
    worker-1:     - SHA256:2b112e5be3d20931fefc5cc2f0ea54b98d4355c8a89fe720444345adca689e5d
    worker-1:     - SHA1:20cba64fab0901f4fd1efc0d0ea37be2750122a0 [weak]
    worker-1:     - MD5Sum:beb867bc65c993ca8dfaa788ecba8b3e [weak]
    worker-1:     - Filesize:42556330 [weak]
    worker-1:    Last modification reported: Wed, 11 Mar 2020 19:46:25 +0000
    worker-1: E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce_19.03.8~3-0~ubuntu-bionic_amd64.deb  Hash Sum mismatch
    worker-1:    Hashes of expected file:
    worker-1:     - SHA512:600f2d9b51024e5866a6256f2d08b4e733a6c8428e334d81de483a7138cbe9db00e8d67673a88d46c80ef0aa673e2f0183f8fd58226575a3a6a843f955c49e2a
    worker-1:     - SHA256:22fe06851dde23200c835641e234760bbb60b79abc3b2a1fbbd1a9b0f1a2e9d0
    worker-1:     - SHA1:7292df34a82e58cab0e45af61036ec19c81eb199 [weak]
    worker-1:     - MD5Sum:8d62aefa851deb2f0739b4a1fd232322 [weak]
    worker-1:     - Filesize:22879338 [weak]
    worker-1:    Hashes of received file:
    worker-1:     - SHA512:eba090be0758293958491020112ff7d99745406a6772065b840d6bd46a0e4c2c131177dc84ca3d42e10e29a3829c4e064a708df1145f89bb2f2154e16e4646c3
    worker-1:     - SHA256:3af5d2c6673c00f125171fb69ad23bdf7c02f2054791a8758966a9cf12768609
    worker-1:     - SHA1:2ec13401b913a81b8a918a4b0a6e0cfc2381b061 [weak]
    worker-1:     - MD5Sum:c010158409e800da994d8b63c3dd5987 [weak]
    worker-1:     - Filesize:22879338 [weak]
    worker-1:    Last modification reported: Wed, 11 Mar 2020 19:46:26 +0000
    worker-1: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Same issue i am also facing unable to complete the HARD Way (really hard)

**Comment by NeoMotsumi** [comment]
Hi 
I know this might probably be late, but make you are using virtualbox 6.0.
https://www.virtualbox.org/wiki/Download_Old_Builds_6_0

**Comment by fireflycons** [comment]
Hi @susilj @NeoMotsumi @mhshamim 

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. 
I realise this is a very old issue, however I was tasked with closing off all old issues following the upgrade.
Please try it now using latest VirtualBox and Vagrant and feel free to raise further issues.

Thanks.
