### ISSUE TITLE
 Error message for  Openssl certificate  creation

### ISSUE THREAD

**Issue by santhoshgk** [mmumshad/kubernetes-the-hard-way#98]
when i try to run
 openssl req -new -key ca.key -subj "/CN=KUBERNETES-CA" -out ca.csr i get the error message 
 as
Can't load /home/vagrant/.rnd into RNG
139958695195072:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/home/vagrant/.rnd

**Comment by santhoshgk** [comment]
i got this resolved thanks

**Comment by ekovacs** [comment]
same happend to me.

the solution was to:

`vim /etc/ssl/openssl.cnf`

and comment out the line with
```
RANDFILE               = $ENV::HOME/.rnd
```
