### ISSUE TITLE
 Error while copying

### ISSUE THREAD

**Issue by santhoshgk** [mmumshad/kubernetes-the-hard-way#99]
While i SCP the certs to the mater nodes... it errors out with
 _Permission denied (publickey)_.

**Comment by fireflycons** [comment]
Hi @santhoshgk 

We have now merged a major change to bring this to v1.24.
Many issues have been addressed as part of the upgrade. 
I realise this is a very old issue, however I was tasked with closing off all old issues following the upgrade.
Please try it now and feel free to raise further issues.

Thanks.
